export const statColors = {
	'hp': '#FF5959',
	'attack': '#F5AC78',
	'defense': '#FAE078',
	'special-attack': '#9DB7F5',
	'special-defense': '#A7DB8D',
	'speed': '#FA92B2',
}

export const statName = {
	'hp': 'HP',
	'attack': 'Atk',
	'defense': 'Def',
	'special-attack': 'SAtk',
	'special-defense': 'SDef',
	'speed': 'Spd',
}

export const dashToRange = str => {
	const [a, b] = str.split('-')
	return Array.from({length: parseInt(b, 10) - parseInt(a, 10) + 1}, (_, i) => i + parseInt(a, 10))
}

export const region1_new = {
	'1-0': [null, 'Bulbasaur', null, 'grass', 'poison'],
	'2-0': [null, 'Ivysaur', null, 'grass', 'poison'],
	'3-0': [null, 'Venusaur', null, 'grass', 'poison'],
	'4-0': [null, 'Charmander', null, 'fire', null],
	'5-0': [null, 'Charmeleon', null, 'fire', null],
	'6-0': [null, 'Charizard', null, 'fire', 'flying'],
	'7-0': [null, 'Squirtle', null, 'water', null],
	'8-0': [null, 'Wartortle', null, 'water', null],
	'9-0': [null, 'Blastoise', null, 'water', null],
	'10-0': [null, 'Caterpie', null, 'bug', null],
	'11-0': [null, 'Metapod', null, 'bug', null],
	'12-0': [null, 'Butterfree', null, 'bug', 'flying'],
	'13-0': [null, 'Weedle', null, 'bug', 'poison'],
	'14-0': [null, 'Kakuna', null, 'bug', 'poison'],
	'15-0': [null, 'Beedrill', null, 'bug', 'poison'],
	'16-0': [null, 'Pidgey', null, 'normal', 'flying'],
	'17-0': [null, 'Pidgeotto', null, 'normal', 'flying'],
	'18-0': [null, 'Pidgeot', null, 'normal', 'flying'],
	'19-0': [null, 'Rattata', null, 'normal', null],
	'20-0': [null, 'Raticate', null, 'normal', null],
	'21-0': [null, 'Spearow', null, 'normal', 'flying'],
	'22-0': [null, 'Fearow', null, 'normal', 'flying'],
	'23-0': [null, 'Ekans', null, 'poison', null],
	'24-0': [null, 'Arbok', null, 'poison', null],
	'25-0': [null, 'Pikachu', null, 'electric', null],
	'26-0': [null, 'Raichu', null, 'electric', null],
	'27-0': [null, 'Sandshrew', null, 'ground', null],
	'28-0': [null, 'Sandslash', null, 'ground', null],
	'29-0': [null, 'Nidoran♀', null, 'poison', null],
	'30-0': [null, 'Nidorina', null, 'poison', null],
	'31-0': [null, 'Nidoqueen', null, 'poison', 'ground'],
	'32-0': [null, 'Nidoran♂', null, 'poison', null],
	'33-0': [null, 'Nidorino', null, 'poison', null],
	'34-0': [null, 'Nidoking', null, 'poison', 'ground'],
	'35-0': [null, 'Clefairy', null, 'fairy', null],
	'36-0': [null, 'Clefable', null, 'fairy', null],
	'37-0': [null, 'Vulpix', null, 'fire', null],
	'38-0': [null, 'Ninetales', null, 'fire', null],
	'39-0': [null, 'Jigglypuff', null, 'normal', 'fairy'],
	'40-0': [null, 'Wigglytuff', null, 'normal', 'fairy'],
	'41-0': [null, 'Zubat', null, 'poison', 'flying'],
	'42-0': [null, 'Golbat', null, 'poison', 'flying'],
	'43-0': [null, 'Oddish', null, 'grass', 'poison'],
	'44-0': [null, 'Gloom', null, 'grass', 'poison'],
	'45-0': [null, 'Vileplume', null, 'grass', 'poison'],
	'46-0': [null, 'Paras', null, 'bug', 'grass'],
	'47-0': [null, 'Parasect', null, 'bug', 'grass'],
	'48-0': [null, 'Venonat', null, 'bug', 'poison'],
	'49-0': [null, 'Venomoth', null, 'bug', 'poison'],
	'50-0': [null, 'Diglett', null, 'ground', null],
	'51-0': [null, 'Dugtrio', null, 'ground', null],
	'52-0': [null, 'Meowth', null, 'normal', null],
	'53-0': [null, 'Persian', null, 'normal', null],
	'54-0': [null, 'Psyduck', null, 'water', null],
	'55-0': [null, 'Golduck', null, 'water', null],
	'56-0': [null, 'Mankey', null, 'fighting', null],
	'57-0': [null, 'Primeape', null, 'fighting', null],
	'58-0': [null, 'Growlithe', null, 'fire', null],
	'59-0': [null, 'Arcanine', null, 'fire', null],
	'60-0': [null, 'Poliwag', null, 'water', null],
	'61-0': [null, 'Poliwhirl', null, 'water', null],
	'62-0': [null, 'Poliwrath', null, 'water', 'fighting'],
	'63-0': [null, 'Abra', null, 'psychic', null],
	'64-0': [null, 'Kadabra', null, 'psychic', null],
	'65-0': [null, 'Alakazam', null, 'psychic', null],
	'66-0': [null, 'Machop', null, 'fighting', null],
	'67-0': [null, 'Machoke', null, 'fighting', null],
	'68-0': [null, 'Machamp', null, 'fighting', null],
	'69-0': [null, 'Bellsprout', null, 'grass', 'poison'],
	'70-0': [null, 'Weepinbell', null, 'grass', 'poison'],
	'71-0': [null, 'Victreebel', null, 'grass', 'poison'],
	'72-0': [null, 'Tentacool', null, 'water', 'poison'],
	'73-0': [null, 'Tentacruel', null, 'water', 'poison'],
	'74-0': [null, 'Geodude', null, 'rock', 'ground'],
	'75-0': [null, 'Graveler', null, 'rock', 'ground'],
	'76-0': [null, 'Golem', null, 'rock', 'ground'],
	'77-0': [null, 'Ponyta', null, 'fire', null],
	'78-0': [null, 'Rapidash', null, 'fire', null],
	'79-0': [null, 'Slowpoke', null, 'water', 'psychic'],
	'80-0': [null, 'Slowbro', null, 'water', 'psychic'],
	'81-0': [null, 'Magnemite', null, 'electric', 'steel'],
	'82-0': [null, 'Magneton', null, 'electric', 'steel'],
	'83-0': [null, "Farfetch'd", null, 'normal', 'flying'],
	'84-0': [null, 'Doduo', null, 'normal', 'flying'],
	'85-0': [null, 'Dodrio', null, 'normal', 'flying'],
	'86-0': [null, 'Seel', null, 'water', null],
	'87-0': [null, 'Dewgong', null, 'water', 'ice'],
	'88-0': [null, 'Grimer', null, 'poison', null],
	'89-0': [null, 'Muk', null, 'poison', null],
	'90-0': [null, 'Shellder', null, 'water', null],
	'91-0': [null, 'Cloyster', null, 'water', 'ice'],
	'92-0': [null, 'Gastly', null, 'ghost', 'poison'],
	'93-0': [null, 'Haunter', null, 'ghost', 'poison'],
	'94-0': [null, 'Gengar', null, 'ghost', 'poison'],
	'95-0': [null, 'Onix', null, 'rock', 'ground'],
	'96-0': [null, 'Drowzee', null, 'psychic', null],
	'97-0': [null, 'Hypno', null, 'psychic', null],
	'98-0': [null, 'Krabby', null, 'water', null],
	'99-0': [null, 'Kingler', null, 'water', null],
	'100-0': [null, 'Voltorb', null, 'electric', null],
	'101-0': [null, 'Electrode', null, 'electric', null],
	'102-0': [null, 'Exeggcute', null, 'grass', 'psychic'],
	'103-0': [null, 'Exeggutor', null, 'grass', 'psychic'],
	'104-0': [null, 'Cubone', null, 'ground', null],
	'105-0': [null, 'Marowak', null, 'ground', null],
	'106-0': [null, 'Hitmonlee', null, 'fighting', null],
	'107-0': [null, 'Hitmonchan', null, 'fighting', null],
	'108-0': [null, 'Lickitung', null, 'normal', null],
	'109-0': [null, 'Koffing', null, 'poison', null],
	'110-0': [null, 'Weezing', null, 'poison', null],
	'111-0': [null, 'Rhyhorn', null, 'ground', 'rock'],
	'112-0': [null, 'Rhydon', null, 'ground', 'rock'],
	'113-0': [null, 'Chansey', null, 'normal', null],
	'114-0': [null, 'Tangela', null, 'grass', null],
	'115-0': [null, 'Kangaskhan', null, 'normal', null],
	'116-0': [null, 'Horsea', null, 'water', null],
	'117-0': [null, 'Seadra', null, 'water', null],
	'118-0': [null, 'Goldeen', null, 'water', null],
	'119-0': [null, 'Seaking', null, 'water', null],
	'120-0': [null, 'Staryu', null, 'water', null],
	'121-0': [null, 'Starmie', null, 'water', 'psychic'],
	'122-0': [null, 'Mr. Mime', null, 'psychic', 'fairy'],
	'123-0': [null, 'Scyther', null, 'bug', 'flying'],
	'124-0': [null, 'Jynx', null, 'ice', 'psychic'],
	'125-0': [null, 'Electabuzz', null, 'electric', null],
	'126-0': [null, 'Magmar', null, 'fire', null],
	'127-0': [null, 'Pinsir', null, 'bug', null],
	'128-0': [null, 'Tauros', null, 'normal', null],
	'129-0': [null, 'Magikarp', null, 'water', null],
	'130-0': [null, 'Gyarados', null, 'water', 'flying'],
	'131-0': [null, 'Lapras', null, 'water', 'ice'],
	'132-0': [null, 'Ditto', null, 'normal', null],
	'133-0': [null, 'Eevee', null, 'normal', null],
	'134-0': [null, 'Vaporeon', null, 'water', null],
	'135-0': [null, 'Jolteon', null, 'electric', null],
	'136-0': [null, 'Flareon', null, 'fire', null],
	'137-0': [null, 'Porygon', null, 'normal', null],
	'138-0': [null, 'Omanyte', null, 'rock', 'water'],
	'139-0': [null, 'Omastar', null, 'rock', 'water'],
	'140-0': [null, 'Kabuto', null, 'rock', 'water'],
	'141-0': [null, 'Kabutops', null, 'rock', 'water'],
	'142-0': [null, 'Aerodactyl', null, 'rock', 'flying'],
	'143-0': [null, 'Snorlax', null, 'normal', null],
	'144-0': [null, 'Articuno', null, 'ice', 'flying'],
	'145-0': [null, 'Zapdos', null, 'electric', 'flying'],
	'146-0': [null, 'Moltres', null, 'fire', 'flying'],
	'147-0': [null, 'Dratini', null, 'dragon', null],
	'148-0': [null, 'Dragonair', null, 'dragon', null],
	'149-0': [null, 'Dragonite', null, 'dragon', 'flying'],
	'150-0': [null, 'Mewtwo', null, 'psychic', null],
	'151-0': [null, 'Mew', null, 'psychic', null],
}

// TODO
// export const region2_old = {}

export const region2_new = {
	'152-0': [null, 'Chikorita', null, 'grass', null],
	'153-0': [null, 'Bayleef', null, 'grass', null],
	'154-0': [null, 'Meganium', null, 'grass', null],
	'155-0': [null, 'Cyndaquil', null, 'fire', null],
	'156-0': [null, 'Quilava', null, 'fire', null],
	'157-0': [null, 'Typhlosion', null, 'fire', null],
	'158-0': [null, 'Totodile', null, 'water', null],
	'159-0': [null, 'Croconaw', null, 'water', null],
	'160-0': [null, 'Feraligatr', null, 'water', null],
	'161-0': [null, 'Sentret', null, 'normal', null],
	'162-0': [null, 'Furret', null, 'normal', null],
	'163-0': [null, 'Hoothoot', null, 'normal', 'flying'],
	'164-0': [null, 'Noctowl', null, 'normal', 'flying'],
	'165-0': [null, 'Ledyba', null, 'bug', 'flying'],
	'166-0': [null, 'Ledian', null, 'bug', 'flying'],
	'167-0': [null, 'Spinarak', null, 'bug', 'poison'],
	'168-0': [null, 'Ariados', null, 'bug', 'poison'],
	'169-0': [null, 'Crobat', null, 'poison', 'flying'],
	'170-0': [null, 'Chinchou', null, 'water', 'electric'],
	'171-0': [null, 'Lanturn', null, 'water', 'electric'],
	'172-0': [null, 'Pichu', null, 'electric', null],
	'173-0': [null, 'Cleffa', null, 'fairy', null],
	'174-0': [null, 'Igglybuff', null, 'normal', 'fairy'],
	'175-0': [null, 'Togepi', null, 'fairy', null],
	'176-0': [null, 'Togetic', null, 'fairy', 'flying'],
	'177-0': [null, 'Natu', null, 'psychic', 'flying'],
	'178-0': [null, 'Xatu', null, 'psychic', 'flying'],
	'179-0': [null, 'Mareep', null, 'electric', null],
	'180-0': [null, 'Flaaffy', null, 'electric', null],
	'181-0': [null, 'Ampharos', null, 'electric', null],
	'182-0': [null, 'Bellossom', null, 'grass', null],
	'183-0': [null, 'Marill', null, 'water', 'fairy'],
	'184-0': [null, 'Azumarill', null, 'water', 'fairy'],
	'185-0': [null, 'Sudowoodo', null, 'rock', null],
	'186-0': [null, 'Politoed', null, 'water', null],
	'187-0': [null, 'Hoppip', null, 'grass', 'flying'],
	'188-0': [null, 'Skiploom', null, 'grass', 'flying'],
	'189-0': [null, 'Jumpluff', null, 'grass', 'flying'],
	'190-0': [null, 'Aipom', null, 'normal', null],
	'191-0': [null, 'Sunkern', null, 'grass', null],
	'192-0': [null, 'Sunflora', null, 'grass', null],
	'193-0': [null, 'Yanma', null, 'bug', 'flying'],
	'194-0': [null, 'Wooper', null, 'water', 'ground'],
	'195-0': [null, 'Quagsire', null, 'water', 'ground'],
	'196-0': [null, 'Espeon', null, 'psychic', null],
	'197-0': [null, 'Umbreon', null, 'dark', null],
	'198-0': [null, 'Murkrow', null, 'dark', 'flying'],
	'199-0': [null, 'Slowking', null, 'water', 'psychic'],
	'200-0': [null, 'Misdreavus', null, 'ghost', null],
	'201-0': [null, 'Unown', null, 'psychic', null],
	'202-0': [null, 'Wobbuffet', null, 'psychic', null],
	'203-0': [null, 'Girafarig', null, 'normal', 'psychic'],
	'204-0': [null, 'Pineco', null, 'bug', null],
	'205-0': [null, 'Forretress', null, 'bug', 'steel'],
	'206-0': [null, 'Dunsparce', null, 'normal', null],
	'207-0': [null, 'Gligar', null, 'ground', 'flying'],
	'208-0': [null, 'Steelix', null, 'steel', 'ground'],
	'209-0': [null, 'Snubbull', null, 'fairy', null],
	'210-0': [null, 'Granbull', null, 'fairy', null],
	'211-0': [null, 'Qwilfish', null, 'water', 'poison'],
	'212-0': [null, 'Scizor', null, 'bug', 'steel'],
	'213-0': [null, 'Shuckle', null, 'bug', 'rock'],
	'214-0': [null, 'Heracross', null, 'bug', 'fighting'],
	'215-0': [null, 'Sneasel', null, 'dark', 'ice'],
	'216-0': [null, 'Teddiursa', null, 'normal', null],
	'217-0': [null, 'Ursaring', null, 'normal', null],
	'218-0': [null, 'Slugma', null, 'fire', null],
	'219-0': [null, 'Magcargo', null, 'fire', 'rock'],
	'220-0': [null, 'Swinub', null, 'ice', 'ground'],
	'221-0': [null, 'Piloswine', null, 'ice', 'ground'],
	'222-0': [null, 'Corsola', null, 'water', 'rock'],
	'223-0': [null, 'Remoraid', null, 'water', null],
	'224-0': [null, 'Octillery', null, 'water', null],
	'225-0': [null, 'Delibird', null, 'ice', 'flying'],
	'226-0': [null, 'Mantine', null, 'water', 'flying'],
	'227-0': [null, 'Skarmory', null, 'steel', 'flying'],
	'228-0': [null, 'Houndour', null, 'dark', 'fire'],
	'229-0': [null, 'Houndoom', null, 'dark', 'fire'],
	'230-0': [null, 'Kingdra', null, 'water', 'dragon'],
	'231-0': [null, 'Phanpy', null, 'ground', null],
	'232-0': [null, 'Donphan', null, 'ground', null],
	'233-0': [null, 'Porygon2', null, 'normal', null],
	'234-0': [null, 'Stantler', null, 'normal', null],
	'235-0': [null, 'Smeargle', null, 'normal', null],
	'236-0': [null, 'Tyrogue', null, 'fighting', null],
	'237-0': [null, 'Hitmontop', null, 'fighting', null],
	'238-0': [null, 'Smoochum', null, 'ice', 'psychic'],
	'239-0': [null, 'Elekid', null, 'electric', null],
	'240-0': [null, 'Magby', null, 'fire', null],
	'241-0': [null, 'Miltank', null, 'normal', null],
	'242-0': [null, 'Blissey', null, 'normal', null],
	'243-0': [null, 'Raikou', null, 'electric', null],
	'244-0': [null, 'Entei', null, 'fire', null],
	'245-0': [null, 'Suicune', null, 'water', null],
	'246-0': [null, 'Larvitar', null, 'rock', 'ground'],
	'247-0': [null, 'Pupitar', null, 'rock', 'ground'],
	'248-0': [null, 'Tyranitar', null, 'rock', 'dark'],
	'249-0': [null, 'Lugia', null, 'psychic', 'flying'],
	'250-0': [null, 'Ho-Oh', null, 'fire', 'flying'],
	'251-0': [null, 'Celebi', null, 'psychic', 'grass'],
}

// TODO
// export const region3_old = {}

export const region3_new = {
	'252-0': [null, 'Treecko', null, 'grass', null],
	'253-0': [null, 'Grovyle', null, 'grass', null],
	'254-0': [null, 'Sceptile', null, 'grass', null],
	'255-0': [null, 'Torchic', null, 'fire', null],
	'256-0': [null, 'Combusken', null, 'fire', 'fighting'],
	'257-0': [null, 'Blaziken', null, 'fire', 'fighting'],
	'258-0': [null, 'Mudkip', null, 'water', null],
	'259-0': [null, 'Marshtomp', null, 'water', 'ground'],
	'260-0': [null, 'Swampert', null, 'water', 'ground'],
	'261-0': [null, 'Poochyena', null, 'dark', null],
	'262-0': [null, 'Mightyena', null, 'dark', null],
	'263-0': [null, 'Zigzagoon', null, 'normal', null],
	'264-0': [null, 'Linoone', null, 'normal', null],
	'265-0': [null, 'Wurmple', null, 'bug', null],
	'266-0': [null, 'Silcoon', null, 'bug', null],
	'267-0': [null, 'Beautifly', null, 'bug', 'flying'],
	'268-0': [null, 'Cascoon', null, 'bug', null],
	'269-0': [null, 'Dustox', null, 'bug', 'poison'],
	'270-0': [null, 'Lotad', null, 'water', 'grass'],
	'271-0': [null, 'Lombre', null, 'water', 'grass'],
	'272-0': [null, 'Ludicolo', null, 'water', 'grass'],
	'273-0': [null, 'Seedot', null, 'grass', null],
	'274-0': [null, 'Nuzleaf', null, 'grass', 'dark'],
	'275-0': [null, 'Shiftry', null, 'grass', 'dark'],
	'276-0': [null, 'Taillow', null, 'normal', 'flying'],
	'277-0': [null, 'Swellow', null, 'normal', 'flying'],
	'278-0': [null, 'Wingull', null, 'water', 'flying'],
	'279-0': [null, 'Pelipper', null, 'water', 'flying'],
	'280-0': [null, 'Ralts', null, 'psychic', 'fairy'],
	'281-0': [null, 'Kirlia', null, 'psychic', 'fairy'],
	'282-0': [null, 'Gardevoir', null, 'psychic', 'fairy'],
	'283-0': [null, 'Surskit', null, 'bug', 'water'],
	'284-0': [null, 'Masquerain', null, 'bug', 'flying'],
	'285-0': [null, 'Shroomish', null, 'grass', null],
	'286-0': [null, 'Breloom', null, 'grass', 'fighting'],
	'287-0': [null, 'Slakoth', null, 'normal', null],
	'288-0': [null, 'Vigoroth', null, 'normal', null],
	'289-0': [null, 'Slaking', null, 'normal', null],
	'290-0': [null, 'Nincada', null, 'bug', 'ground'],
	'291-0': [null, 'Ninjask', null, 'bug', 'flying'],
	'292-0': [null, 'Shedinja', null, 'bug', 'ghost'],
	'293-0': [null, 'Whismur', null, 'normal', null],
	'294-0': [null, 'Loudred', null, 'normal', null],
	'295-0': [null, 'Exploud', null, 'normal', null],
	'296-0': [null, 'Makuhita', null, 'fighting', null],
	'297-0': [null, 'Hariyama', null, 'fighting', null],
	'298-0': [null, 'Azurill', null, 'normal', 'fairy'],
	'299-0': [null, 'Nosepass', null, 'rock', null],
	'300-0': [null, 'Skitty', null, 'normal', null],
	'301-0': [null, 'Delcatty', null, 'normal', null],
	'302-0': [null, 'Sableye', null, 'dark', 'ghost'],
	'303-0': [null, 'Mawile', null, 'steel', 'fairy'],
	'304-0': [null, 'Aron', null, 'steel', 'rock'],
	'305-0': [null, 'Lairon', null, 'steel', 'rock'],
	'306-0': [null, 'Aggron', null, 'steel', 'rock'],
	'307-0': [null, 'Meditite', null, 'fighting', 'psychic'],
	'308-0': [null, 'Medicham', null, 'fighting', 'psychic'],
	'309-0': [null, 'Electrike', null, 'electric', null],
	'310-0': [null, 'Manectric', null, 'electric', null],
	'311-0': [null, 'Plusle', null, 'electric', null],
	'312-0': [null, 'Minun', null, 'electric', null],
	'313-0': [null, 'Volbeat', null, 'bug', null],
	'314-0': [null, 'Illumise', null, 'bug', null],
	'315-0': [null, 'Roselia', null, 'grass', 'poison'],
	'316-0': [null, 'Gulpin', null, 'poison', null],
	'317-0': [null, 'Swalot', null, 'poison', null],
	'318-0': [null, 'Carvanha', null, 'water', 'dark'],
	'319-0': [null, 'Sharpedo', null, 'water', 'dark'],
	'320-0': [null, 'Wailmer', null, 'water', null],
	'321-0': [null, 'Wailord', null, 'water', null],
	'322-0': [null, 'Numel', null, 'fire', 'ground'],
	'323-0': [null, 'Camerupt', null, 'fire', 'ground'],
	'324-0': [null, 'Torkoal', null, 'fire', null],
	'325-0': [null, 'Spoink', null, 'psychic', null],
	'326-0': [null, 'Grumpig', null, 'psychic', null],
	'327-0': [null, 'Spinda', null, 'normal', null],
	'328-0': [null, 'Trapinch', null, 'ground', null],
	'329-0': [null, 'Vibrava', null, 'ground', 'dragon'],
	'330-0': [null, 'Flygon', null, 'ground', 'dragon'],
	'331-0': [null, 'Cacnea', null, 'grass', null],
	'332-0': [null, 'Cacturne', null, 'grass', 'dark'],
	'333-0': [null, 'Swablu', null, 'normal', 'flying'],
	'334-0': [null, 'Altaria', null, 'dragon', 'flying'],
	'335-0': [null, 'Zangoose', null, 'normal', null],
	'336-0': [null, 'Seviper', null, 'poison', null],
	'337-0': [null, 'Lunatone', null, 'rock', 'psychic'],
	'338-0': [null, 'Solrock', null, 'rock', 'psychic'],
	'339-0': [null, 'Barboach', null, 'water', 'ground'],
	'340-0': [null, 'Whiscash', null, 'water', 'ground'],
	'341-0': [null, 'Corphish', null, 'water', null],
	'342-0': [null, 'Crawdaunt', null, 'water', 'dark'],
	'343-0': [null, 'Baltoy', null, 'ground', 'psychic'],
	'344-0': [null, 'Claydol', null, 'ground', 'psychic'],
	'345-0': [null, 'Lileep', null, 'rock', 'grass'],
	'346-0': [null, 'Cradily', null, 'rock', 'grass'],
	'347-0': [null, 'Anorith', null, 'rock', 'bug'],
	'348-0': [null, 'Armaldo', null, 'rock', 'bug'],
	'349-0': [null, 'Feebas', null, 'water', null],
	'350-0': [null, 'Milotic', null, 'water', null],
	'351-0': [null, 'Castform', null, 'normal', null],
	'352-0': [null, 'Kecleon', null, 'normal', null],
	'353-0': [null, 'Shuppet', null, 'ghost', null],
	'354-0': [null, 'Banette', null, 'ghost', null],
	'355-0': [null, 'Duskull', null, 'ghost', null],
	'356-0': [null, 'Dusclops', null, 'ghost', null],
	'357-0': [null, 'Tropius', null, 'grass', 'flying'],
	'358-0': [null, 'Chimecho', null, 'psychic', null],
	'359-0': [null, 'Absol', null, 'dark', null],
	'360-0': [null, 'Wynaut', null, 'psychic', null],
	'361-0': [null, 'Snorunt', null, 'ice', null],
	'362-0': [null, 'Glalie', null, 'ice', null],
	'363-0': [null, 'Spheal', null, 'ice', 'water'],
	'364-0': [null, 'Sealeo', null, 'ice', 'water'],
	'365-0': [null, 'Walrein', null, 'ice', 'water'],
	'366-0': [null, 'Clamperl', null, 'water', null],
	'367-0': [null, 'Huntail', null, 'water', null],
	'368-0': [null, 'Gorebyss', null, 'water', null],
	'369-0': [null, 'Relicanth', null, 'water', 'rock'],
	'370-0': [null, 'Luvdisc', null, 'water', null],
	'371-0': [null, 'Bagon', null, 'dragon', null],
	'372-0': [null, 'Shelgon', null, 'dragon', null],
	'373-0': [null, 'Salamence', null, 'dragon', 'flying'],
	'374-0': [null, 'Beldum', null, 'steel', 'psychic'],
	'375-0': [null, 'Metang', null, 'steel', 'psychic'],
	'376-0': [null, 'Metagross', null, 'steel', 'psychic'],
	'377-0': [null, 'Regirock', null, 'rock', null],
	'378-0': [null, 'Regice', null, 'ice', null],
	'379-0': [null, 'Registeel', null, 'steel', null],
	'380-0': [null, 'Latias', null, 'dragon', 'psychic'],
	'381-0': [null, 'Latios', null, 'dragon', 'psychic'],
	'382-0': [null, 'Kyogre', null, 'water', null],
	'383-0': [null, 'Groudon', null, 'ground', null],
	'384-0': [null, 'Rayquaza', null, 'dragon', 'flying'],
	'385-0': [null, 'Jirachi', null, 'steel', 'psychic'],
	'386-0': [null, 'Deoxys', null, 'psychic', null],
}

// TODO
// export const region4_old = {}

export const region4_new = {
	'387-0': [null, 'Turtwig', null, 'grass', null],
	'388-0': [null, 'Grotle', null, 'grass', null],
	'389-0': [null, 'Torterra', null, 'grass', 'ground'],
	'390-0': [null, 'Chimchar', null, 'fire', null],
	'391-0': [null, 'Monferno', null, 'fire', 'fighting'],
	'392-0': [null, 'Infernape', null, 'fire', 'fighting'],
	'393-0': [null, 'Piplup', null, 'water', null],
	'394-0': [null, 'Prinplup', null, 'water', null],
	'395-0': [null, 'Empoleon', null, 'water', 'steel'],
	'396-0': [null, 'Starly', null, 'normal', 'flying'],
	'397-0': [null, 'Staravia', null, 'normal', 'flying'],
	'398-0': [null, 'Staraptor', null, 'normal', 'flying'],
	'399-0': [null, 'Bidoof', null, 'normal', null],
	'400-0': [null, 'Bibarel', null, 'normal', 'water'],
	'401-0': [null, 'Kricketot', null, 'bug', null],
	'402-0': [null, 'Kricketune', null, 'bug', null],
	'403-0': [null, 'Shinx', null, 'electric', null],
	'404-0': [null, 'Luxio', null, 'electric', null],
	'405-0': [null, 'Luxray', null, 'electric', null],
	'406-0': [null, 'Budew', null, 'grass', 'poison'],
	'407-0': [null, 'Roserade', null, 'grass', 'poison'],
	'408-0': [null, 'Cranidos', null, 'rock', null],
	'409-0': [null, 'Rampardos', null, 'rock', null],
	'410-0': [null, 'Shieldon', null, 'rock', 'steel'],
	'411-0': [null, 'Bastiodon', null, 'rock', 'steel'],
	'412-0': [null, 'Burmy', null, 'bug', null],
	'413-0': [null, 'Wormadam', null, 'bug', 'grass'],
	'414-0': [null, 'Mothim', null, 'bug', 'flying'],
	'415-0': [null, 'Combee', null, 'bug', 'flying'],
	'416-0': [null, 'Vespiquen', null, 'bug', 'flying'],
	'417-0': [null, 'Pachirisu', null, 'electric', null],
	'418-0': [null, 'Buizel', null, 'water', null],
	'419-0': [null, 'Floatzel', null, 'water', null],
	'420-0': [null, 'Cherubi', null, 'grass', null],
	'421-0': [null, 'Cherrim', null, 'grass', null],
	'422-0': [null, 'Shellos', null, 'water', null],
	'423-0': [null, 'Gastrodon', null, 'water', 'ground'],
	'424-0': [null, 'Ambipom', null, 'normal', null],
	'425-0': [null, 'Drifloon', null, 'ghost', 'flying'],
	'426-0': [null, 'Drifblim', null, 'ghost', 'flying'],
	'427-0': [null, 'Buneary', null, 'normal', null],
	'428-0': [null, 'Lopunny', null, 'normal', null],
	'429-0': [null, 'Mismagius', null, 'ghost', null],
	'430-0': [null, 'Honchkrow', null, 'dark', 'flying'],
	'431-0': [null, 'Glameow', null, 'normal', null],
	'432-0': [null, 'Purugly', null, 'normal', null],
	'433-0': [null, 'Chingling', null, 'psychic', null],
	'434-0': [null, 'Stunky', null, 'poison', 'dark'],
	'435-0': [null, 'Skuntank', null, 'poison', 'dark'],
	'436-0': [null, 'Bronzor', null, 'steel', 'psychic'],
	'437-0': [null, 'Bronzong', null, 'steel', 'psychic'],
	'438-0': [null, 'Bonsly', null, 'rock', null],
	'439-0': [null, 'Mime Jr.', null, 'psychic', 'fairy'],
	'440-0': [null, 'Happiny', null, 'normal', null],
	'441-0': [null, 'Chatot', null, 'normal', 'flying'],
	'442-0': [null, 'Spiritomb', null, 'ghost', 'dark'],
	'443-0': [null, 'Gible', null, 'dragon', 'ground'],
	'444-0': [null, 'Gabite', null, 'dragon', 'ground'],
	'445-0': [null, 'Garchomp', null, 'dragon', 'ground'],
	'446-0': [null, 'Munchlax', null, 'normal', null],
	'447-0': [null, 'Riolu', null, 'fighting', null],
	'448-0': [null, 'Lucario', null, 'fighting', 'steel'],
	'449-0': [null, 'Hippopotas', null, 'ground', null],
	'450-0': [null, 'Hippowdon', null, 'ground', null],
	'451-0': [null, 'Skorupi', null, 'poison', 'bug'],
	'452-0': [null, 'Drapion', null, 'poison', 'dark'],
	'453-0': [null, 'Croagunk', null, 'poison', 'fighting'],
	'454-0': [null, 'Toxicroak', null, 'poison', 'fighting'],
	'455-0': [null, 'Carnivine', null, 'grass', null],
	'456-0': [null, 'Finneon', null, 'water', null],
	'457-0': [null, 'Lumineon', null, 'water', null],
	'458-0': [null, 'Mantyke', null, 'water', 'flying'],
	'459-0': [null, 'Snover', null, 'grass', 'ice'],
	'460-0': [null, 'Abomasnow', null, 'grass', 'ice'],
	'461-0': [null, 'Weavile', null, 'dark', 'ice'],
	'462-0': [null, 'Magnezone', null, 'electric', 'steel'],
	'463-0': [null, 'Lickilicky', null, 'normal', null],
	'464-0': [null, 'Rhyperior', null, 'ground', 'rock'],
	'465-0': [null, 'Tangrowth', null, 'grass', null],
	'466-0': [null, 'Electivire', null, 'electric', null],
	'467-0': [null, 'Magmortar', null, 'fire', null],
	'468-0': [null, 'Togekiss', null, 'fairy', 'flying'],
	'469-0': [null, 'Yanmega', null, 'bug', 'flying'],
	'470-0': [null, 'Leafeon', null, 'grass', null],
	'471-0': [null, 'Glaceon', null, 'ice', null],
	'472-0': [null, 'Gliscor', null, 'ground', 'flying'],
	'473-0': [null, 'Mamoswine', null, 'ice', 'ground'],
	'474-0': [null, 'Porygon-Z', null, 'normal', null],
	'475-0': [null, 'Gallade', null, 'psychic', 'fighting'],
	'476-0': [null, 'Probopass', null, 'rock', 'steel'],
	'477-0': [null, 'Dusknoir', null, 'ghost', null],
	'478-0': [null, 'Froslass', null, 'ice', 'ghost'],
	'479-0': [null, 'Rotom', null, 'electric', 'ghost'],
	'480-0': [null, 'Uxie', null, 'psychic', null],
	'481-0': [null, 'Mesprit', null, 'psychic', null],
	'482-0': [null, 'Azelf', null, 'psychic', null],
	'483-0': [null, 'Dialga', null, 'steel', 'dragon'],
	'484-0': [null, 'Palkia', null, 'water', 'dragon'],
	'485-0': [null, 'Heatran', null, 'fire', 'steel'],
	'486-0': [null, 'Regigigas', null, 'normal', null],
	'487-0': [null, 'Giratina', null, 'ghost', 'dragon'],
	'488-0': [null, 'Cresselia', null, 'psychic', null],
	'489-0': [null, 'Phione', null, 'water', null],
	'490-0': [null, 'Manaphy', null, 'water', null],
	'491-0': [null, 'Darkrai', null, 'dark', null],
	'492-0': [null, 'Shaymin', null, 'grass', null],
	'493-0': [null, 'Arceus', null, 'normal', null],
}

export const region5_new = {
	'494-0': [null, 'Victini', null, 'psychic', 'fire'],
	'495-0': [null, 'Snivy', null, 'grass', null],
	'496-0': [null, 'Servine', null, 'grass', null],
	'497-0': [null, 'Serperior', null, 'grass', null],
	'498-0': [null, 'Tepig', null, 'fire', null],
	'499-0': [null, 'Pignite', null, 'fire', 'fighting'],
	'500-0': [null, 'Emboar', null, 'fire', 'fighting'],
	'501-0': [null, 'Oshawott', null, 'water', null],
	'502-0': [null, 'Dewott', null, 'water', null],
	'503-0': [null, 'Samurott', null, 'water', null],
	'504-0': [null, 'Patrat', null, 'normal', null],
	'505-0': [null, 'Watchog', null, 'normal', null],
	'506-0': [null, 'Lillipup', null, 'normal', null],
	'507-0': [null, 'Herdier', null, 'normal', null],
	'508-0': [null, 'Stoutland', null, 'normal', null],
	'509-0': [null, 'Purrloin', null, 'dark', null],
	'510-0': [null, 'Liepard', null, 'dark', null],
	'511-0': [null, 'Pansage', null, 'grass', null],
	'512-0': [null, 'Simisage', null, 'grass', null],
	'513-0': [null, 'Pansear', null, 'fire', null],
	'514-0': [null, 'Simisear', null, 'fire', null],
	'515-0': [null, 'Panpour', null, 'water', null],
	'516-0': [null, 'Simipour', null, 'water', null],
	'517-0': [null, 'Munna', null, 'psychic', null],
	'518-0': [null, 'Musharna', null, 'psychic', null],
	'519-0': [null, 'Pidove', null, 'normal', 'flying'],
	'520-0': [null, 'Tranquill', null, 'normal', 'flying'],
	'521-0': [null, 'Unfezant', null, 'normal', 'flying'],
	'522-0': [null, 'Blitzle', null, 'electric', null],
	'523-0': [null, 'Zebstrika', null, 'electric', null],
	'524-0': [null, 'Roggenrola', null, 'rock', null],
	'525-0': [null, 'Boldore', null, 'rock', null],
	'526-0': [null, 'Gigalith', null, 'rock', null],
	'527-0': [null, 'Woobat', null, 'psychic', 'flying'],
	'528-0': [null, 'Swoobat', null, 'psychic', 'flying'],
	'529-0': [null, 'Drilbur', null, 'ground', null],
	'530-0': [null, 'Excadrill', null, 'ground', 'steel'],
	'531-0': [null, 'Audino', null, 'normal', null],
	'532-0': [null, 'Timburr', null, 'fighting', null],
	'533-0': [null, 'Gurdurr', null, 'fighting', null],
	'534-0': [null, 'Conkeldurr', null, 'fighting', null],
	'535-0': [null, 'Tympole', null, 'water', null],
	'536-0': [null, 'Palpitoad', null, 'water', 'ground'],
	'537-0': [null, 'Seismitoad', null, 'water', 'ground'],
	'538-0': [null, 'Throh', null, 'fighting', null],
	'539-0': [null, 'Sawk', null, 'fighting', null],
	'540-0': [null, 'Sewaddle', null, 'bug', 'grass'],
	'541-0': [null, 'Swadloon', null, 'bug', 'grass'],
	'542-0': [null, 'Leavanny', null, 'bug', 'grass'],
	'543-0': [null, 'Venipede', null, 'bug', 'poison'],
	'544-0': [null, 'Whirlipede', null, 'bug', 'poison'],
	'545-0': [null, 'Scolipede', null, 'bug', 'poison'],
	'546-0': [null, 'Cottonee', null, 'grass', 'fairy'],
	'547-0': [null, 'Whimsicott', null, 'grass', 'fairy'],
	'548-0': [null, 'Petilil', null, 'grass', null],
	'549-0': [null, 'Lilligant', null, 'grass', null],
	'550-0': [null, 'Basculin', null, 'water', null],
	'551-0': [null, 'Sandile', null, 'ground', 'dark'],
	'552-0': [null, 'Krokorok', null, 'ground', 'dark'],
	'553-0': [null, 'Krookodile', null, 'ground', 'dark'],
	'554-0': [null, 'Darumaka', null, 'fire', null],
	'555-0': [null, 'Darmanitan', null, 'fire', null],
	'556-0': [null, 'Maractus', null, 'grass', null],
	'557-0': [null, 'Dwebble', null, 'bug', 'rock'],
	'558-0': [null, 'Crustle', null, 'bug', 'rock'],
	'559-0': [null, 'Scraggy', null, 'dark', 'fighting'],
	'560-0': [null, 'Scrafty', null, 'dark', 'fighting'],
	'561-0': [null, 'Sigilyph', null, 'psychic', 'flying'],
	'562-0': [null, 'Yamask', null, 'ghost', null],
	'563-0': [null, 'Cofagrigus', null, 'ghost', null],
	'564-0': [null, 'Tirtouga', null, 'water', 'rock'],
	'565-0': [null, 'Carracosta', null, 'water', 'rock'],
	'566-0': [null, 'Archen', null, 'rock', 'flying'],
	'567-0': [null, 'Archeops', null, 'rock', 'flying'],
	'568-0': [null, 'Trubbish', null, 'poison', null],
	'569-0': [null, 'Garbodor', null, 'poison', null],
	'570-0': [null, 'Zorua', null, 'dark', null],
	'571-0': [null, 'Zoroark', null, 'dark', null],
	'572-0': [null, 'Minccino', null, 'normal', null],
	'573-0': [null, 'Cinccino', null, 'normal', null],
	'574-0': [null, 'Gothita', null, 'psychic', null],
	'575-0': [null, 'Gothorita', null, 'psychic', null],
	'576-0': [null, 'Gothitelle', null, 'psychic', null],
	'577-0': [null, 'Solosis', null, 'psychic', null],
	'578-0': [null, 'Duosion', null, 'psychic', null],
	'579-0': [null, 'Reuniclus', null, 'psychic', null],
	'580-0': [null, 'Ducklett', null, 'water', 'flying'],
	'581-0': [null, 'Swanna', null, 'water', 'flying'],
	'582-0': [null, 'Vanillite', null, 'ice', null],
	'583-0': [null, 'Vanillish', null, 'ice', null],
	'584-0': [null, 'Vanilluxe', null, 'ice', null],
	'585-0': [null, 'Deerling', 'Spring Form', 'normal', 'grass'],
	'586-0': [null, 'Sawsbuck', 'Spring Form', 'normal', 'grass'],
	'587-0': [null, 'Emolga', null, 'electric', 'flying'],
	'588-0': [null, 'Karrablast', null, 'bug', null],
	'589-0': [null, 'Escavalier', null, 'bug', 'steel'],
	'590-0': [null, 'Foongus', null, 'grass', 'poison'],
	'591-0': [null, 'Amoonguss', null, 'grass', 'poison'],
	'592-0': [null, 'Frillish', null, 'water', 'ghost'],
	'593-0': [null, 'Jellicent', null, 'water', 'ghost'],
	'594-0': [null, 'Alomomola', null, 'water', null],
	'595-0': [null, 'Joltik', null, 'bug', 'electric'],
	'596-0': [null, 'Galvantula', null, 'bug', 'electric'],
	'597-0': [null, 'Ferroseed', null, 'grass', 'steel'],
	'598-0': [null, 'Ferrothorn', null, 'grass', 'steel'],
	'599-0': [null, 'Klink', null, 'steel', null],
	'600-0': [null, 'Klang', null, 'steel', null],
	'601-0': [null, 'Klinklang', null, 'steel', null],
	'602-0': [null, 'Tynamo', null, 'electric', null],
	'603-0': [null, 'Eelektrik', null, 'electric', null],
	'604-0': [null, 'Eelektross', null, 'electric', null],
	'605-0': [null, 'Elgyem', null, 'psychic', null],
	'606-0': [null, 'Beheeyem', null, 'psychic', null],
	'607-0': [null, 'Litwick', null, 'ghost', 'fire'],
	'608-0': [null, 'Lampent', null, 'ghost', 'fire'],
	'609-0': [null, 'Chandelure', null, 'ghost', 'fire'],
	'610-0': [null, 'Axew', null, 'dragon', null],
	'611-0': [null, 'Fraxure', null, 'dragon', null],
	'612-0': [null, 'Haxorus', null, 'dragon', null],
	'613-0': [null, 'Cubchoo', null, 'ice', null],
	'614-0': [null, 'Beartic', null, 'ice', null],
	'615-0': [null, 'Cryogonal', null, 'ice', null],
	'616-0': [null, 'Shelmet', null, 'bug', null],
	'617-0': [null, 'Accelgor', null, 'bug', null],
	'618-0': [null, 'Stunfisk', null, 'ground', 'electric'],
	'619-0': [null, 'Mienfoo', null, 'fighting', null],
	'620-0': [null, 'Mienshao', null, 'fighting', null],
	'621-0': [null, 'Druddigon', null, 'dragon', null],
	'622-0': [null, 'Golett', null, 'ground', 'ghost'],
	'623-0': [null, 'Golurk', null, 'ground', 'ghost'],
	'624-0': [null, 'Pawniard', null, 'dark', 'steel'],
	'625-0': [null, 'Bisharp', null, 'dark', 'steel'],
	'626-0': [null, 'Bouffalant', null, 'normal', null],
	'627-0': [null, 'Rufflet', null, 'normal', 'flying'],
	'628-0': [null, 'Braviary', null, 'normal', 'flying'],
	'629-0': [null, 'Vullaby', null, 'dark', 'flying'],
	'630-0': [null, 'Mandibuzz', null, 'dark', 'flying'],
	'631-0': [null, 'Heatmor', null, 'fire', null],
	'632-0': [null, 'Durant', null, 'bug', 'steel'],
	'633-0': [null, 'Deino', null, 'dark', 'dragon'],
	'634-0': [null, 'Zweilous', null, 'dark', 'dragon'],
	'635-0': [null, 'Hydreigon', null, 'dark', 'dragon'],
	'636-0': [null, 'Larvesta', null, 'bug', 'fire'],
	'637-0': [null, 'Volcarona', null, 'bug', 'fire'],
	'638-0': [null, 'Cobalion', null, 'steel', 'fighting'],
	'639-0': [null, 'Terrakion', null, 'rock', 'fighting'],
	'640-0': [null, 'Virizion', null, 'grass', 'fighting'],
	'641-0': [null, 'Tornadus', null, 'flying', null],
	'642-0': [null, 'Thundurus', null, 'electric', 'flying'],
	'643-0': [null, 'Reshiram', null, 'dragon', 'fire'],
	'644-0': [null, 'Zekrom', null, 'dragon', 'electric'],
	'645-0': [null, 'Landorus', null, 'ground', 'flying'],
	'646-0': [null, 'Kyurem', null, 'dragon', 'ice'],
	'647-0': [null, 'Keldeo', null, 'water', 'fighting'],
	'648-0': [null, 'Meloetta', null, 'normal', 'psychic'],
	'649-0': [null, 'Genesect', null, 'bug', 'steel'],
}

export const region6_new = {
	'650-0': [null, 'Chespin', null, 'grass', null],
	'651-0': [null, 'Quilladin', null, 'grass', null],
	'652-0': [null, 'Chesnaught', null, 'grass', 'fighting'],
	'653-0': [null, 'Fennekin', null, 'fire', null],
	'654-0': [null, 'Braixen', null, 'fire', null],
	'655-0': [null, 'Delphox', null, 'fire', 'psychic'],
	'656-0': [null, 'Froakie', null, 'water', null],
	'657-0': [null, 'Frogadier', null, 'water', null],
	'658-0': [null, 'Greninja', null, 'water', 'dark'],
	'659-0': [null, 'Bunnelby', null, 'normal', null],
	'660-0': [null, 'Diggersby', null, 'normal', 'ground'],
	'661-0': [null, 'Fletchling', null, 'normal', 'flying'],
	'662-0': [null, 'Fletchinder', null, 'fire', 'flying'],
	'663-0': [null, 'Talonflame', null, 'fire', 'flying'],
	'664-0': [null, 'Scatterbug', null, 'bug', null],
	'665-0': [null, 'Spewpa', null, 'bug', null],
	'666-0': [null, 'Vivillon', null, 'bug', 'flying'],
	'667-0': [null, 'Litleo', null, 'fire', 'normal'],
	'668-0': [null, 'Pyroar', null, 'fire', 'normal'],
	'669-0': [null, 'Flabébé', null, 'fairy', null],
	'670-0': [null, 'Floette', null, 'fairy', null],
	'671-0': [null, 'Florges', null, 'fairy', null],
	'672-0': [null, 'Skiddo', null, 'grass', null],
	'673-0': [null, 'Gogoat', null, 'grass', null],
	'674-0': [null, 'Pancham', null, 'fighting', null],
	'675-0': [null, 'Pangoro', null, 'fighting', 'dark'],
	'676-0': [null, 'Furfrou', null, 'normal', null],
	'677-0': [null, 'Espurr', null, 'psychic', null],
	'678-0': [null, 'Meowstic', null, 'psychic', null],
	'679-0': [null, 'Honedge', null, 'steel', 'ghost'],
	'680-0': [null, 'Doublade', null, 'steel', 'ghost'],
	'681-0': [null, 'Aegislash', null, 'steel', 'ghost'],
	'682-0': [null, 'Spritzee', null, 'fairy', null],
	'683-0': [null, 'Aromatisse', null, 'fairy', null],
	'684-0': [null, 'Swirlix', null, 'fairy', null],
	'685-0': [null, 'Slurpuff', null, 'fairy', null],
	'686-0': [null, 'Inkay', null, 'dark', 'psychic'],
	'687-0': [null, 'Malamar', null, 'dark', 'psychic'],
	'688-0': [null, 'Binacle', null, 'rock', 'water'],
	'689-0': [null, 'Barbaracle', null, 'rock', 'water'],
	'690-0': [null, 'Skrelp', null, 'poison', 'water'],
	'691-0': [null, 'Dragalge', null, 'poison', 'dragon'],
	'692-0': [null, 'Clauncher', null, 'water', null],
	'693-0': [null, 'Clawitzer', null, 'water', null],
	'694-0': [null, 'Helioptile', null, 'electric', 'normal'],
	'695-0': [null, 'Heliolisk', null, 'electric', 'normal'],
	'696-0': [null, 'Tyrunt', null, 'rock', 'dragon'],
	'697-0': [null, 'Tyrantrum', null, 'rock', 'dragon'],
	'698-0': [null, 'Amaura', null, 'rock', 'ice'],
	'699-0': [null, 'Aurorus', null, 'rock', 'ice'],
	'700-0': [null, 'Sylveon', null, 'fairy', null],
	'701-0': [null, 'Hawlucha', null, 'fighting', 'flying'],
	'702-0': [null, 'Dedenne', null, 'electric', 'fairy'],
	'703-0': [null, 'Carbink', null, 'rock', 'fairy'],
	'704-0': [null, 'Goomy', null, 'dragon', null],
	'705-0': [null, 'Sliggoo', null, 'dragon', null],
	'706-0': [null, 'Goodra', null, 'dragon', null],
	'707-0': [null, 'Klefki', null, 'steel', 'fairy'],
	'708-0': [null, 'Phantump', null, 'ghost', 'grass'],
	'709-0': [null, 'Trevenant', null, 'ghost', 'grass'],
	'710-0': [null, 'Pumpkaboo', null, 'ghost', 'grass'],
	'711-0': [null, 'Gourgeist', null, 'ghost', 'grass'],
	'712-0': [null, 'Bergmite', null, 'ice', null],
	'713-0': [null, 'Avalugg', null, 'ice', null],
	'714-0': [null, 'Noibat', null, 'flying', 'dragon'],
	'715-0': [null, 'Noivern', null, 'flying', 'dragon'],
	'716-0': [null, 'Xerneas', null, 'fairy', null],
	'717-0': [null, 'Yveltal', null, 'dark', 'flying'],
	'718-0': [null, 'Zygarde', null, 'dragon', 'ground'],
	'719-0': [null, 'Diancie', null, 'rock', 'fairy'],
	'720-0': [null, 'Hoopa', null, 'psychic', 'dark'],
	'721-0': [null, 'Volcanion', null, 'fire', 'water'],
}

export const region6_mega = {
	'3-1': ['Mega', 'Venusaur', null, 'grass', 'poison'],
	'6-1': ['Mega', 'Charizard X', null, 'fire', 'dragon'],
	'6-2': ['Mega', 'Charizard Y', null, 'fire', 'flying'],
	'9-1': ['Mega', 'Blastoise', null, 'water', null],
	'15-1': ['Mega', 'Beedrill', null, 'bug', 'poison'],
	'18-1': ['Mega', 'Pidgeot', null, 'normal', 'flying'],
	'65-1': ['Mega', 'Alakazam', null, 'psychic', null],
	'80-1': ['Mega', 'Slowbro', null, 'water', 'psychic'],
	'94-1': ['Mega', 'Gengar', null, 'ghost', 'poison'],
	'115-1': ['Mega', 'Kangaskhan', null, 'normal', null],
	'127-1': ['Mega', 'Pinsir', null, 'bug', 'flying'],
	'130-1': ['Mega', 'Gyarados', null, 'water', 'dark'],
	'142-1': ['Mega', 'Aerodactyl', null, 'rock', 'flying'],
	'150-1': ['Mega', 'Mewtwo X', null, 'psychic', 'fighting'],
	'150-2': ['Mega', 'Mewtwo Y', null, 'psychic', null],
	'181-1': ['Mega', 'Ampharos', null, 'electric', 'dragon'],
	'212-1': ['Mega', 'Scizor', null, 'bug', 'steel'],
	'208-1': ['Mega', 'Steelix', null, 'steel', 'ground'],
	'214-1': ['Mega', 'Heracross', null, 'bug', 'fighting'],
	'229-1': ['Mega', 'Houndoom', null, 'dark', 'fire'],
	'248-1': ['Mega', 'Tyranitar', null, 'rock', 'dark'],
	'254-1': ['Mega', 'Sceptile', null, 'grass', 'dragon'],
	'257-1': ['Mega', 'Blaziken', null, 'fire', 'fighting'],
	'260-1': ['Mega', 'Swampert', null, 'water', 'ground'],
	'282-1': ['Mega', 'Gardevoir', null, 'psychic', 'fairy'],
	'302-1': ['Mega', 'Sableye', null, 'dark', 'ghost'],
	'303-1': ['Mega', 'Mawile', null, 'steel', 'fairy'],
	'306-1': ['Mega', 'Aggron', null, 'steel', null],
	'308-1': ['Mega', 'Medicham', null, 'fighting', 'psychic'],
	'310-1': ['Mega', 'Manectric', null, 'electric', null],
	'319-1': ['Mega', 'Sharpedo', null, 'water', 'dark'],
	'323-1': ['Mega', 'Camerupt', null, 'fire', 'ground'],
	'334-1': ['Mega', 'Altaria', null, 'dragon', 'fairy'],
	'354-1': ['Mega', 'Banette', null, 'ghost', null],
	'359-1': ['Mega', 'Absol', null, 'dark', null],
	'362-1': ['Mega', 'Glalie', null, 'ice', null],
	'373-1': ['Mega', 'Salamence', null, 'dragon', 'flying'],
	'376-1': ['Mega', 'Metagross', null, 'steel', 'psychic'],
	'380-1': ['Mega', 'Latias', null, 'dragon', 'psychic'],
	'381-1': ['Mega', 'Latios', null, 'dragon', 'psychic'],
	'382-1': ['Primal', 'Kyogre', null, 'water', null],
	'383-1': ['Primal', 'Groudon', null, 'fire', 'ground'],
	'384-1': ['Mega', 'Rayquaza', null, 'dragon', 'flying'],
	'428-1': ['Mega', 'Lopunny', null, 'normal', 'fighting'],
	'445-1': ['Mega', 'Garchomp', null, 'dragon', 'ground'],
	'448-1': ['Mega', 'Lucario', null, 'fighting', 'steel'],
	'460-1': ['Mega', 'Abomasnow', null, 'grass', 'ice'],
	'475-1': ['Mega', 'Gallade', null, 'psychic', 'fighting'],
	'531-1': ['Mega', 'Audino', null, 'normal', 'fairy'],
	'719-1': ['Mega', 'Diancie', null, 'rock', 'fairy'],
}

export const region7_old = {
	'19-1': ['Alolan', 'Rattata', null, 'dark', 'normal'],
	'20-1': ['Alolan', 'Raticate', null, 'dark', 'normal'],
	'25-1': [null, 'Pikachu', 'Original Cap', 'electric', null],
	'25-2': [null, 'Pikachu', 'Hoenn Cap', 'electric', null],
	'25-3': [null, 'Pikachu', 'Sinnoh Cap', 'electric', null],
	'25-4': [null, 'Pikachu', 'Unova Cap', 'electric', null],
	'25-5': [null, 'Pikachu', 'Kalos Cap', 'electric', null],
	'25-6': [null, 'Pikachu', 'Alola Cap', 'electric', null],
	'25-7': [null, 'Pikachu', 'Partner Cap', 'electric', null],
	'25-8': [null, 'Pikachu', 'World Cap', 'electric', null],
	'26-1': ['Alolan', 'Raichu', null, 'electric', 'psychic'],
	'27-1': ['Alolan', 'Sandshrew', null, 'ice', 'steel'],
	'28-1': ['Alolan', 'Sandslash', null, 'ice', 'steel'],
	'37-1': ['Alolan', 'Vulpix', null, 'ice', null],
	'38-1': ['Alolan', 'Ninetales', null, 'ice', 'fairy'],
	'50-1': ['Alolan', 'Diglett', null, 'ground', 'steel'],
	'51-1': ['Alolan', 'Dugtrio', null, 'ground', 'steel'],
	'52-1': ['Alolan', 'Meowth', null, 'dark', null],
	'53-1': ['Alolan', 'Persian', null, 'dark', null],
	'74-1': ['Alolan', 'Geodude', null, 'rock', 'electric'],
	'75-1': ['Alolan', 'Graveler', null, 'rock', 'electric'],
	'76-1': ['Alolan', 'Golem', null, 'rock', 'electric'],
	'88-1': ['Alolan', 'Grimer', null, 'poison', 'dark'],
	'89-1': ['Alolan', 'Muk', null, 'poison', 'dark'],
	'102-0': [null, 'Exeggcute', null, 'grass', 'psychic'],
	'103-1': ['Alolan', 'Exeggutor', null, 'grass', 'dragon'],
	'104-0': [null, 'Cubone', null, 'ground', null],
	'105-1': ['Alolan', 'Marowak', null, 'fire', 'ghost'],
	'658-2': ['Ash', 'Greninja', null, 'water', 'dark'],
}

export const region7_new = {
	'722-0': [null, 'Rowlet', null, 'grass', 'flying'],
	'723-0': [null, 'Dartrix', null, 'grass', 'flying'],
	'724-0': [null, 'Decidueye', null, 'grass', 'ghost'],
	'724-1': [null, 'Decidueye', 'Hisuian Form', 'grass', 'fighting'],
	'725-0': [null, 'Litten', null, 'fire', null],
	'726-0': [null, 'Torracat', null, 'fire', null],
	'727-0': [null, 'Incineroar', null, 'fire', 'dark'],
	'728-0': [null, 'Popplio', null, 'water', null],
	'729-0': [null, 'Brionne', null, 'water', null],
	'730-0': [null, 'Primarina', null, 'water', 'fairy'],
	'731-0': [null, 'Pikipek', null, 'normal', 'flying'],
	'732-0': [null, 'Trumbeak', null, 'normal', 'flying'],
	'733-0': [null, 'Toucannon', null, 'normal', 'flying'],
	'734-0': [null, 'Yungoos', null, 'normal', null],
	'735-0': [null, 'Gumshoos', null, 'normal', null],
	'736-0': [null, 'Grubbin', null, 'bug', null],
	'737-0': [null, 'Charjabug', null, 'bug', 'electric'],
	'738-0': [null, 'Vikavolt', null, 'bug', 'electric'],
	'739-0': [null, 'Crabrawler', null, 'fighting', null],
	'740-0': [null, 'Crabominable', null, 'fighting', 'ice'],
	'741-0': [null, 'Oricorio', "Baile Style", 'fire', 'flying'],
	'741-1': [null, 'Oricorio', "Pom-Pom Style", 'electric', 'flying'],
	'741-2': [null, 'Oricorio', "Pa'u Style", 'psychic', 'flying'],
	'741-3': [null, 'Oricorio', "Sensu Style", 'ghost', 'flying'],
	'742-0': [null, 'Cutiefly', null, 'bug', 'fairy'],
	'743-0': [null, 'Ribombee', null, 'bug', 'fairy'],
	'744-0': [null, 'Rockruff', null, 'rock', null],
	'745-0': [null, 'Lycanroc', 'Midday Form', 'rock', null],
	'745-1': [null, 'Lycanroc', 'Midnight Form', 'rock', null],
	'745-2': [null, 'Lycanroc', 'Dusk Form', 'rock', null],
	'746-0': [null, 'Wishiwashi', 'Solo Form', 'water', null],
	'746-1': [null, 'Wishiwashi', 'School Form', 'water', null],
	'747-0': [null, 'Mareanie', null, 'poison', 'water'],
	'748-0': [null, 'Toxapex', null, 'poison', 'water'],
	'749-0': [null, 'Mudbray', null, 'ground', null],
	'750-0': [null, 'Mudsdale', null, 'ground', null],
	'751-0': [null, 'Dewpider', null, 'water', 'bug'],
	'752-0': [null, 'Araquanid', null, 'water', 'bug'],
	'753-0': [null, 'Fomantis', null, 'grass', null],
	'754-0': [null, 'Lurantis', null, 'grass', null],
	'755-0': [null, 'Morelull', null, 'grass', 'fairy'],
	'756-0': [null, 'Shiinotic', null, 'grass', 'fairy'],
	'757-0': [null, 'Salandit', null, 'poison', 'fire'],
	'758-0': [null, 'Salazzle', null, 'poison', 'fire'],
	'759-0': [null, 'Stufful', null, 'normal', 'fighting'],
	'760-0': [null, 'Bewear', null, 'normal', 'fighting'],
	'761-0': [null, 'Bounsweet', null, 'grass', null],
	'762-0': [null, 'Steenee', null, 'grass', null],
	'763-0': [null, 'Tsareena', null, 'grass', null],
	'764-0': [null, 'Comfey', null, 'fairy', null],
	'765-0': [null, 'Oranguru', null, 'normal', 'psychic'],
	'766-0': [null, 'Passimian', null, 'fighting', null],
	'767-0': [null, 'Wimpod', null, 'bug', 'water'],
	'768-0': [null, 'Golisopod', null, 'bug', 'water'],
	'769-0': [null, 'Sandygast', null, 'ghost', 'ground'],
	'770-0': [null, 'Palossand', null, 'ghost', 'ground'],
	'771-0': [null, 'Pyukumuku', null, 'water', null],
	'772-0': [null, 'Type: Null', null, 'normal', null],
	'773-0': [null, 'Silvally', "Type: Normal", 'normal', null],
	'774-0': [null, 'Minior', 'Meteor Form', 'rock', 'flying'],
	'774-7': [null, 'Minior', 'Red Core', 'rock', 'flying'],
	'775-0': [null, 'Komala', null, 'normal', null],
	'776-0': [null, 'Turtonator', null, 'fire', 'dragon'],
	'777-0': [null, 'Togedemaru', null, 'electric', 'steel'],
	'778-0': [null, 'Mimikyu', null, 'ghost', 'fairy'],
	'779-0': [null, 'Bruxish', null, 'water', 'psychic'],
	'780-0': [null, 'Drampa', null, 'normal', 'dragon'],
	'781-0': [null, 'Dhelmise', null, 'ghost', 'grass'],
	'782-0': [null, 'Jangmo-o', null, 'dragon', null],
	'783-0': [null, 'Hakamo-o', null, 'dragon', 'fighting'],
	'784-0': [null, 'Kommo-o', null, 'dragon', 'fighting'],
	'785-0': [null, 'Tapu Koko', null, 'electric', 'fairy'],
	'786-0': [null, 'Tapu Lele', null, 'psychic', 'fairy'],
	'787-0': [null, 'Tapu Bulu', null, 'grass', 'fairy'],
	'788-0': [null, 'Tapu Fini', null, 'water', 'fairy'],
	'789-0': [null, 'Cosmog', null, 'psychic', null],
	'790-0': [null, 'Cosmoem', null, 'psychic', null],
	'791-0': [null, 'Solgaleo', null, 'psychic', 'steel'],
	'792-0': [null, 'Lunala', null, 'psychic', 'ghost'],
	'793-0': [null, 'Nihilego', null, 'rock', 'poison'],
	'794-0': [null, 'Buzzwole', null, 'bug', 'fighting'],
	'795-0': [null, 'Pheromosa', null, 'bug', 'fighting'],
	'796-0': [null, 'Xurkitree', null, 'electric', null],
	'797-0': [null, 'Celesteela', null, 'steel', 'flying'],
	'798-0': [null, 'Kartana', null, 'grass', 'steel'],
	'799-0': [null, 'Guzzlord', null, 'dark', 'dragon'],
	'800-0': [null, 'Necrozma', null, 'psychic', null],
	'800-1': [null, 'Necrozma', 'Dusk Mane', 'psychic', 'steel'],
	'800-2': [null, 'Necrozma', 'Dawn Wings', 'psychic', 'ghost'],
	'800-3': ['Ultra', 'Necrozma', null, 'psychic', 'dragon'],
	'801-0': [null, 'Magearna', null, 'steel', 'fairy'],
	'802-0': [null, 'Marshadow', null, 'fighting', 'ghost'],
	'803-0': [null, 'Poipole', null, 'poison', null],
	'804-0': [null, 'Naganadel', null, 'poison', 'dragon'],
	'805-0': [null, 'Stakataka', null, 'rock', 'steel'],
	'806-0': [null, 'Blacephalon', null, 'fire', 'ghost'],
	'807-0': [null, 'Zeraora', null, 'electric', null],
	'808-0': [null, 'Meltan', null, 'steel', null],
	'809-0': [null, 'Melmetal', null, 'steel', null],
}

export const region7_totems = {
	'20-1t': ['Totem Alolan', 'Raticate', null, 'dark', 'normal'],
	'105-1t': ['Totem Alolan', 'Marowak', null, 'fire', 'ghost'],
	'735-0t': ['Totem', 'Gumshoos', null, 'normal', null],
	'738-0t': ['Totem', 'Vikavolt', null, 'bug', 'electric'],
	'743-0t': ['Totem', 'Ribombee', null, 'bug', 'fairy'],
	'752-0t': ['Totem', 'Araquanid', null, 'water', 'bug'],
	'754-0t': ['Totem', 'Lurantis', null, 'grass', null],
	'758-0t': ['Totem', 'Salazzle', null, 'poison', 'fire'],
	'777-0t': ['Totem', 'Togedemaru', null, 'electric', 'steel'],
	'778-0t': ['Totem', 'Mimikyu', null, 'ghost', 'fairy'],
	'784-0t': ['Totem', 'Kommo-o', null, 'dragon', 'fighting'],
}

export const region8a_old = {
	'52-2': ['Galarian', 'Meowth', null, 'steel', null],
	'863-0': ['Galarian', 'Perrserker', null, 'steel', null],
	'77-1': ['Galarian', 'Ponyta', null, 'psychic', null],
	'78-1': ['Galarian', 'Rapidash', null, 'psychic', 'fairy'],
	'79-1': ['Galarian', 'Slowpoke', null, 'psychic', null],
	'80-2': ['Galarian', 'Slowbro', null, 'poison', 'psychic'],
	'199-1': ['Galarian', 'Slowking', null, 'poison', 'psychic'],
	'83-1': ['Galarian', "Farfetch'd", null, 'fighting', null],
	'865-0': ['Galarian', "Sirfetch'd", null, 'fighting', null],
	'109-0': [null, 'Koffing', null, 'poison', null],
	'110-1': ['Galarian', 'Weezing', null, 'poison', 'fairy'],
	'439-0': [null, 'Mime Jr.', null, 'psychic', 'fairy'],
	'122-1': ['Galarian', 'Mr. Mime', null, 'ice', 'psychic'],
	'866-0': ['Galarian', 'Mr. Rime', null, 'ice', 'psychic'],
	'144-1': ['Galarian', 'Articuno', null, 'psychic', 'flying'],
	'145-1': ['Galarian', 'Zapdos', null, 'fighting', 'flying'],
	'146-1': ['Galarian', 'Moltres', null, 'dark', 'flying'],
	'222-1': ['Galarian', 'Corsola', null, 'ghost', null],
	'864-0': ['Galarian', 'Cursola', null, 'ghost', null],
	'263-1': ['Galarian', 'Zigzagoon', null, 'dark', 'normal'],
	'264-1': ['Galarian', 'Linoone', null, 'dark', 'normal'],
	'862-0': ['Galarian', 'Obstagoon', null, 'dark', 'normal'],
	'554-1': ['Galarian', 'Darumaka', null, 'ice', null],
	'555-1': ['Galarian', 'Darmanitan', null, 'ice', null],
	'555-3': ['Galarian', 'Darmanitan', 'Zen Mode', 'ice', 'fire'],
	'562-1': ['Galarian', 'Yamask', null, 'ground', 'ghost'],
	'867-0': ['Galarian', 'Runerigus', null, 'ground', 'ghost'],
	'618-1': ['Galarian', 'Stunfisk', null, 'ground', 'steel'],
}

export const region8a_new = {
	'810-0': [null, 'Grookey', null, 'grass', null],
	'811-0': [null, 'Thwackey', null, 'grass', null],
	'812-0': [null, 'Rillaboom', null, 'grass', null],
	'813-0': [null, 'Scorbunny', null, 'fire', null],
	'814-0': [null, 'Raboot', null, 'fire', null],
	'815-0': [null, 'Cinderace', null, 'fire', null],
	'816-0': [null, 'Sobble', null, 'water', null],
	'817-0': [null, 'Drizzile', null, 'water', null],
	'818-0': [null, 'Inteleon', null, 'water', null],
	'819-0': [null, 'Skwovet', null, 'normal', null],
	'820-0': [null, 'Greedent', null, 'normal', null],
	'821-0': [null, 'Rookidee', null, 'flying', null],
	'822-0': [null, 'Corvisquire', null, 'flying', null],
	'823-0': [null, 'Corviknight', null, 'flying', 'steel'],
	'824-0': [null, 'Blipbug', null, 'bug', null],
	'825-0': [null, 'Dottler', null, 'bug', 'psychic'],
	'826-0': [null, 'Orbeetle', null, 'bug', 'psychic'],
	'827-0': [null, 'Nickit', null, 'dark', null],
	'828-0': [null, 'Thievul', null, 'dark', null],
	'829-0': [null, 'Gossifleur', null, 'grass', null],
	'830-0': [null, 'Eldegoss', null, 'grass', null],
	'831-0': [null, 'Wooloo', null, 'normal', null],
	'832-0': [null, 'Dubwool', null, 'normal', null],
	'833-0': [null, 'Chewtle', null, 'water', null],
	'834-0': [null, 'Drednaw', null, 'water', 'rock'],
	'835-0': [null, 'Yamper', null, 'electric', null],
	'836-0': [null, 'Boltund', null, 'electric', null],
	'837-0': [null, 'Rolycoly', null, 'rock', null],
	'838-0': [null, 'Carkol', null, 'rock', 'fire'],
	'839-0': [null, 'Coalossal', null, 'rock', 'fire'],
	'840-0': [null, 'Applin', null, 'grass', 'dragon'],
	'841-0': [null, 'Flapple', null, 'grass', 'dragon'],
	'842-0': [null, 'Appletun', null, 'grass', 'dragon'],
	'843-0': [null, 'Silicobra', null, 'ground', null],
	'844-0': [null, 'Sandaconda', null, 'ground', null],
	'845-0': [null, 'Cramorant', null, 'flying', 'water'],
	'845-1': [null, 'Cramorant', 'Gulping Form', 'flying', 'water'],
	'845-2': [null, 'Cramorant', 'Gorging Form', 'flying', 'water'],
	'846-0': [null, 'Arrokuda', null, 'water', null],
	'847-0': [null, 'Barraskewda', null, 'water', null],
	'848-0': [null, 'Toxel', null, 'electric', 'poison'],
	'849-0': [null, 'Toxtricity', 'Amped Form', 'electric', 'poison'],
	'849-1': [null, 'Toxtricity', 'Low Key Form', 'electric', 'poison'],
	'850-0': [null, 'Sizzlipede', null, 'fire', 'bug'],
	'851-0': [null, 'Centiskorch', null, 'fire', 'bug'],
	'852-0': [null, 'Clobbopus', null, 'fighting', null],
	'853-0': [null, 'Grapploct', null, 'fighting', null],
	'854-0': [null, 'Sinistea', null, 'ghost', null],
	'855-0': [null, 'Polteageist', null, 'ghost', null],
	'856-0': [null, 'Hatenna', null, 'psychic', null],
	'857-0': [null, 'Hattrem', null, 'psychic', null],
	'858-0': [null, 'Hatterene', null, 'psychic', 'fairy'],
	'859-0': [null, 'Impidimp', null, 'dark', 'fairy'],
	'860-0': [null, 'Morgrem', null, 'dark', 'fairy'],
	'861-0': [null, 'Grimmsnarl', null, 'dark', 'fairy'],
	'862-0': [null, 'Obstagoon', null, 'dark', 'normal'],
	'863-0': [null, 'Perrserker', null, 'steel', null],
	'864-0': [null, 'Cursola', null, 'ghost', null],
	'865-0': [null, "Sirfetch'd", null, 'fighting', null],
	'866-0': [null, 'Mr. Rime', null, 'ice', 'psychic'],
	'867-0': [null, 'Runerigus', null, 'ground', 'ghost'],
	'868-0': [null, 'Milcery', null, 'fairy', null],
	'869-0': [null, 'Alcremie', 'Vanilla Cream', 'fairy', null],
	'870-0': [null, 'Falinks', null, 'fighting', null],
	'871-0': [null, 'Pincurchin', null, 'electric', null],
	'872-0': [null, 'Snom', null, 'ice', 'bug'],
	'873-0': [null, 'Frosmoth', null, 'ice', 'bug'],
	'874-0': [null, 'Stonjourner', null, 'rock', null],
	'875-0': [null, 'Eiscue', 'Ice Face', 'ice', null],
	'875-1': [null, 'Eiscue', 'Noice Face', 'ice', null],
	'876-0': [null, 'Indeedee', 'Male', 'psychic', 'normal'],
	'876-1': [null, 'Indeedee', 'Female', 'psychic', 'normal'],
	'877-0': [null, 'Morpeko', 'Full Belly Mode', 'electric', 'dark'],
	'877-1': [null, 'Morpeko', 'Hangry Mode', 'dark', 'electric'],
	'878-0': [null, 'Cufant', null, 'steel', null],
	'879-0': [null, 'Copperajah', null, 'steel', null],
	'880-0': [null, 'Dracozolt', null, 'electric', 'dragon'],
	'881-0': [null, 'Arctozolt', null, 'electric', 'ice'],
	'882-0': [null, 'Dracovish', null, 'water', 'dragon'],
	'883-0': [null, 'Arctovish', null, 'water', 'ice'],
	'884-0': [null, 'Duraludon', null, 'steel', 'dragon'],
	'885-0': [null, 'Dreepy', null, 'dragon', 'ghost'],
	'886-0': [null, 'Drakloak', null, 'dragon', 'ghost'],
	'887-0': [null, 'Dragapult', null, 'dragon', 'ghost'],
	'888-0': [null, 'Zacian', 'Hero of Many Battles', 'fairy', null],
	'888-1': [null, 'Zacian', 'Crowned Sword', 'fairy', 'steel'],
	'889-0': [null, 'Zamazenta', 'Hero of Many Battles', 'fighting', null],
	'889-1': [null, 'Zamazenta', 'Crowned Shield', 'fighting', 'steel'],
	'890-0': [null, 'Eternatus', null, 'poison', 'dragon'],
	'891-0': [null, 'Kubfu', null, 'fighting', null],
	'892-0': [null, 'Urshifu', 'Single Strike Style', 'fighting', 'dark'],
	'892-0r': [null, 'Urshifu', 'Rapid Strike Style', 'fighting', 'water'],
	'893-0': [null, 'Zarude', null, 'dark', 'grass'],
	'894-0': [null, 'Regieleki', null, 'electric', null],
	'895-0': [null, 'Regidrago', null, 'dragon', null],
	'896-0': [null, 'Glastrier', null, 'ice', null],
	'897-0': [null, 'Spectrier', null, 'ghost', null],
	'898-0': [null, 'Calyrex', null, 'psychic', 'grass'],
	'898-1': [null, 'Calyrex', 'Ice Rider', 'psychic', 'ice'],
	'898-2': [null, 'Calyrex', 'Shadow Rider', 'psychic', 'ghost'],
}

export const region8a_gmax = {
	'3-0g': ['Gigantamax', 'Venusaur', null, 'grass', 'poison'],
	'6-0g': ['Gigantamax', 'Charizard', null, 'fire', 'flying'],
	'9-0g': ['Gigantamax', 'Blastoise', null, 'water', null],
	'12-0g': ['Gigantamax', 'Butterfree', null, 'bug', 'flying'],
	'25-0g': ['Gigantamax', 'Pikachu', null, 'electric', null],
	'52-0g': ['Gigantamax', 'Meowth', null, 'normal', null],
	'68-0g': ['Gigantamax', 'Machamp', null, 'fighting', null],
	'94-0g': ['Gigantamax', 'Gengar', null, 'ghost', 'poison'],
	'99-0g': ['Gigantamax', 'Kingler', null, 'water', null],
	'131-0g': ['Gigantamax', 'Lapras', null, 'ice', 'water'],
	'133-0g': ['Gigantamax', 'Eevee', null, 'normal', null],
	'143-0g': ['Gigantamax', 'Snorlax', null, 'normal', null],
	'569-0g': ['Gigantamax', 'Garbodor', null, 'poison', null],
	'809-0g': ['Gigantamax', 'Melmetal', null, 'steel', null],
	'812-0g': ['Gigantamax', 'Rillaboom', null, 'grass', null],
	'815-0g': ['Gigantamax', 'Cinderace', null, 'fire', null],
	'818-0g': ['Gigantamax', 'Inteleon', null, 'water', null],
	'823-0g': ['Gigantamax', 'Corviknight', null, 'flying', 'steel'],
	'826-0g': ['Gigantamax', 'Orbeetle', null, 'psychic', 'bug'],
	'834-0g': ['Gigantamax', 'Drednaw', null, 'water', 'rock'],
	'839-0g': ['Gigantamax', 'Coalossal', null, 'rock', 'fire'],
	'841-0g': ['Gigantamax', 'Flapple', null, 'grass', 'dragon'],
	'842-0g': ['Gigantamax', 'Appletun', null, 'grass', 'dragon'],
	'844-0g': ['Gigantamax', 'Sandaconda', null, 'ground', null],
	'849-0g': ['Gigantamax', 'Toxtricity', null, 'electric', 'poison'],
	'851-0g': ['Gigantamax', 'Centiskorch', null, 'fire', 'bug'],
	'858-0g': ['Gigantamax', 'Hatterene', null, 'fairy', 'psychic'],
	'861-0g': ['Gigantamax', 'Grimmsnarl', null, 'dark', 'fairy'],
	'869-0g': ['Gigantamax', 'Alcremie', null, 'fairy', null],
	'879-0g': ['Gigantamax', 'Copperajah', null, 'steel', null],
	'884-0g': ['Gigantamax', 'Duraludon', null, 'steel', 'dragon'],
	'892-0g1': ['Gigantamax', 'Urshifu', 'Single Strike', 'dark', 'fighting'],
	'892-0g2': ['Gigantamax', 'Urshifu', 'Rapid Strike', 'water', 'fighting'],
}

export const region8b_old = {
	'58-1': ['Hisuian', 'Growlithe', null, 'fire', 'rock'],
	'59-1': ['Hisuian', 'Arcanine', null, 'fire', 'rock'],
	'100-1': ['Hisuian', 'Voltorb', null, 'electric', 'grass'],
	'101-1': ['Hisuian', 'Electrode', null, 'electric', 'grass'],
	'123-0': [null, 'Scyther', null, 'bug', 'flying'],
	'900-0': ['Hisuian', 'Kleavor', null, 'bug', 'rock'],
	'155-0': [null, 'Cyndaquil', null, 'fire', null],
	'156-0': [null, 'Quilava', null, 'fire', null],
	'157-1': ['Hisuian', 'Typhlosion', null, 'fire', 'ghost'],
	'211-1': ['Hisuian', 'Qwilfish', null, 'dark', 'poison'],
	'904-0': ['Hisuian', 'Overqwil', null, 'dark', 'poison'],
	'215-1': ['Hisuian', 'Sneasel', null, 'fighting', 'poison'],
	'903-0': ['Hisuian', 'Sneasler', null, 'fighting', 'poison'],
	'216-0': [null, 'Teddiursa', null, 'normal', null],
	'217-0': [null, 'Ursaring', null, 'normal', null],
	'901-0': ['Hisuian', 'Ursaluna', null, 'ground', 'normal'],
	'234-0': [null, 'Stantler', null, 'normal', null],
	'899-0': ['Hisuian', 'Wyrdeer', null, 'normal', 'psychic'],
	'501-0': [null, 'Oshawott', null, 'water', null],
	'502-0': [null, 'Dewott', null, 'water', null],
	'503-1': ['Hisuian', 'Samurott', null, 'water', 'dark'],
	'548-0': [null, 'Petilil', null, 'grass', null],
	'549-1': ['Hisuian', 'Lilligant', null, 'grass', 'fighting'],
	'550-0': [null, 'Basculin', 'Red-Striped Form', 'water', null],
	'550-1': [null, 'Basculin', 'Blue-Striped Form', 'water', null],
	'550-2': ['Hisuian', 'Basculin', 'White-Striped Form', 'water', null],
	'902-0': ['Hisuian', 'Basculegion', 'Male', 'water', 'ghost'],
	'902-1': ['Hisuian', 'Basculegion', 'Female', 'water', 'ghost'],
	'570-1': ['Hisuian', 'Zorua', null, 'normal', 'ghost'],
	'571-1': ['Hisuian', 'Zoroark', null, 'normal', 'ghost'],
	'627-0': [null, 'Rufflet', null, 'normal', 'flying'],
	'628-1': ['Hisuian', 'Braviary', null, 'psychic', 'flying'],
	'704-0': [null, 'Goomy', null, 'dragon', null],
	'705-1': ['Hisuian', 'Sliggoo', null, 'steel', 'dragon'],
	'706-1': ['Hisuian', 'Goodra', null, 'steel', 'dragon'],
	'712-0': [null, 'Bergmite', null, 'ice', null],
	'713-1': ['Hisuian', 'Avalugg', null, 'ice', 'rock'],
	'722-0': [null, 'Rowlet', null, 'grass', 'flying'],
	'723-0': [null, 'Dartrix', null, 'grass', 'flying'],
	'724-1': ['Hisuian', 'Decidueye', null, 'grass', 'fighting'],
}

export const region8b_new = {
	'899-0': [null, 'Wyrdeer', null, 'normal', 'psychic'],
	'900-0': [null, 'Kleavor', null, 'bug', 'rock'],
	'901-0': [null, 'Ursaluna', null, 'ground', 'normal'],
	'902-0': [null, 'Basculegion', 'Male', 'water', 'ghost'],
	'902-1': [null, 'Basculegion', 'Female', 'water', 'ghost'],
	'903-0': [null, 'Sneasler', null, 'fighting', 'poison'],
	'904-0': [null, 'Overqwil', null, 'dark', 'poison'],
	'905-0': [null, 'Enamorus', 'Incarnate Forme', 'fairy', 'flying'],
	'905-1': [null, 'Enamorus', 'Therian Forme', 'fairy', 'flying'],
}

export const region9a_old = {
	'56-0': [null, 'Mankey', null, 'fighting', null],
	'57-0': [null, 'Primeape', null, 'fighting', null],
	'979-0': ['Paldean', 'Annihilape', null, 'fighting', 'ghost'],
	'128-1': ['Paldean', 'Tauros', 'Combat Breed', 'fighting', null],
	'128-2': ['Paldean', 'Tauros', 'Blaze Breed', 'fighting', 'fire'],
	'128-3': ['Paldean', 'Tauros', 'Aqua Breed', 'fighting', 'water'],
	'194-1': ['Paldean', 'Wooper', null, 'poison', 'ground'],
	'980-0': ['Paldean', 'Clodsire', null, 'poison', 'ground'],
	'203-0': [null, 'Girafarig', null, 'normal', 'psychic'],
	'981-0': ['Paldean', 'Farigiraf', null, 'normal', 'psychic'],
	'206-0': [null, 'Dunsparce', null, 'normal', null],
	'982-0': ['Paldean', 'Dudunsparce', null, 'normal', null],
	'624-0': [null, 'Pawniard', null, 'dark', 'steel'],
	'625-0': [null, 'Bisharp', null, 'dark', 'steel'],
	'983-0': ['Paldean', 'Kingambit', null, 'dark', 'steel'],
}

export const region9a_new = {
	'906-0': [null, 'Sprigatito', null, 'grass', null],
	'907-0': [null, 'Floragato', null, 'grass', null],
	'908-0': [null, 'Meowscarada', null, 'grass', 'dark'],
	'909-0': [null, 'Fuecoco', null, 'fire', null],
	'910-0': [null, 'Crocalor', null, 'fire', null],
	'911-0': [null, 'Skeledirge', null, 'fire', 'ghost'],
	'912-0': [null, 'Quaxly', null, 'water', null],
	'913-0': [null, 'Quaxwell', null, 'water', null],
	'914-0': [null, 'Quaquaval', null, 'water', 'fighting'],
	'915-0': [null, 'Lechonk', null, 'normal', null],
	'916-0': [null, 'Oinkologne', null, 'normal', null],
	'917-0': [null, 'Tarountula', null, 'bug', null],
	'918-0': [null, 'Spidops', null, 'bug', null],
	'919-0': [null, 'Nymble', null, 'bug', null],
	'920-0': [null, 'Lokix', null, 'bug', 'dark'],
	'921-0': [null, 'Pawmi', null, 'electric', null],
	'922-0': [null, 'Pawmo', null, 'electric', 'fighting'],
	'923-0': [null, 'Pawmot', null, 'electric', 'fighting'],
	'924-0': [null, 'Tandemaus', null, 'normal', null],
	'925-0': [null, 'Maushold', null, 'normal', null],
	'926-0': [null, 'Fidough', null, 'fairy', null],
	'927-0': [null, 'Dachsbun', null, 'fairy', null],
	'928-0': [null, 'Smoliv', null, 'grass', 'normal'],
	'929-0': [null, 'Dolliv', null, 'grass', 'normal'],
	'930-0': [null, 'Arboliva', null, 'grass', 'normal'],
	'931-0': [null, 'Squawkabilly', null, 'normal', 'flying'],
	'932-0': [null, 'Nacli', null, 'rock', null],
	'933-0': [null, 'Naclstack', null, 'rock', null],
	'934-0': [null, 'Garganacl', null, 'rock', null],
	'935-0': [null, 'Charcadet', null, 'fire', null],
	'936-0': [null, 'Armarouge', null, 'fire', 'psychic'],
	'937-0': [null, 'Ceruledge', null, 'fire', 'ghost'],
	'938-0': [null, 'Tadbulb', null, 'electric', null],
	'939-0': [null, 'Bellibolt', null, 'electric', null],
	'940-0': [null, 'Wattrel', null, 'electric', 'flying'],
	'941-0': [null, 'Kilowattrel', null, 'electric', 'flying'],
	'942-0': [null, 'Maschiff', null, 'dark', null],
	'943-0': [null, 'Mabosstiff', null, 'dark', null],
	'944-0': [null, 'Shroodle', null, 'poison', 'normal'],
	'945-0': [null, 'Grafaiai', null, 'poison', 'normal'],
	'946-0': [null, 'Bramblin', null, 'grass', 'ghost'],
	'947-0': [null, 'Brambleghast', null, 'grass', 'ghost'],
	'948-0': [null, 'Toedscool', null, 'ground', 'grass'],
	'949-0': [null, 'Toedscruel', null, 'ground', 'grass'],
	'950-0': [null, 'Klawf', null, 'rock', null],
	'951-0': [null, 'Capsakid', null, 'grass', null],
	'952-0': [null, 'Scovillain', null, 'grass', 'fire'],
	'953-0': [null, 'Rellor', null, 'bug', null],
	'954-0': [null, 'Rabsca', null, 'bug', 'psychic'],
	'955-0': [null, 'Flittle', null, 'psychic', null],
	'956-0': [null, 'Espathra', null, 'psychic', null],
	'957-0': [null, 'Tinkatink', null, 'fairy', 'steel'],
	'958-0': [null, 'Tinkatuff', null, 'fairy', 'steel'],
	'959-0': [null, 'Tinkaton', null, 'fairy', 'steel'],
	'960-0': [null, 'Wiglett', null, 'water', null],
	'961-0': [null, 'Wugtrio', null, 'water', null],
	'962-0': [null, 'Bombirdier', null, 'flying', 'dark'],
	'963-0': [null, 'Finizen', null, 'water', null],
	'964-0': [null, 'Palafin', 'Zero Form', 'water', null],
	'964-1': [null, 'Palafin', 'Hero Form', 'water', null],
	'965-0': [null, 'Varoom', null, 'steel', 'poison'],
	'966-0': [null, 'Revavroom', null, 'steel', 'poison'],
	'967-0': [null, 'Cyclizar', null, 'dragon', 'normal'],
	'968-0': [null, 'Orthworm', null, 'steel', null],
	'969-0': [null, 'Glimmet', null, 'rock', 'poison'],
	'970-0': [null, 'Glimmora', null, 'rock', 'poison'],
	'971-0': [null, 'Greavard', null, 'ghost', null],
	'972-0': [null, 'Houndstone', null, 'ghost', null],
	'973-0': [null, 'Flamigo', null, 'flying', 'fighting'],
	'974-0': [null, 'Cetoddle', null, 'ice', null],
	'975-0': [null, 'Cetitan', null, 'ice', null],
	'976-0': [null, 'Veluza', null, 'water', 'psychic'],
	'977-0': [null, 'Dondozo', null, 'water', null],
	'978-0': [null, 'Tatsugiri', 'Curly Form', 'dragon', 'water'],
	'978-1': [null, 'Tatsugiri', 'Droopy Form', 'dragon', 'water'],
	'978-2': [null, 'Tatsugiri', 'Stretchy Form', 'dragon', 'water'],
	'979-0': [null, 'Annihilape', null, 'fighting', 'ghost'],
	'980-0': [null, 'Clodsire', null, 'poison', 'ground'],
	'981-0': [null, 'Farigiraf', null, 'normal', 'psychic'],
	'982-0': [null, 'Dudunsparce', null, 'normal', null],
	'983-0': [null, 'Kingambit', null, 'dark', 'steel'],
	'984-0': [null, 'Great Tusk', null, 'ground', 'fighting'],
	'985-0': [null, 'Scream Tail', null, 'fairy', 'psychic'],
	'986-0': [null, 'Brute Bonnet', null, 'grass', 'dark'],
	'987-0': [null, 'Flutter Mane', null, 'ghost', 'fairy'],
	'988-0': [null, 'Slither Wing', null, 'bug', 'fighting'],
	'989-0': [null, 'Sandy Shocks', null, 'electric', 'ground'],
	'990-0': [null, 'Iron Treads', null, 'ground', 'steel'],
	'991-0': [null, 'Iron Bundle', null, 'ice', 'water'],
	'992-0': [null, 'Iron Hands', null, 'fighting', 'electric'],
	'993-0': [null, 'Iron Jugulis', null, 'dark', 'flying'],
	'994-0': [null, 'Iron Moth', null, 'fire', 'poison'],
	'995-0': [null, 'Iron Thorns', null, 'rock', 'electric'],
	'996-0': [null, 'Frigibax', null, 'dragon', 'ice'],
	'997-0': [null, 'Arctibax', null, 'dragon', 'ice'],
	'998-0': [null, 'Baxcalibur', null, 'dragon', 'ice'],
	'999-0': [null, 'Gimmighoul', 'Chest Form', 'ghost', null],
	'999-1': [null, 'Gimmighoul', 'Roaming Form', 'ghost', null],
	'1000-0': [null, 'Gholdengo', null, 'steel', 'ghost'],
	'1001-0': [null, 'Wo-Chien', null, 'dark', 'grass'],
	'1002-0': [null, 'Chien-Pao', null, 'dark', 'ice'],
	'1003-0': [null, 'Ting-Lu', null, 'dark', 'ground'],
	'1004-0': [null, 'Chi-Yu', null, 'dark', 'fire'],
	'1005-0': [null, 'Roaring Moon', null, 'dragon', 'dark'],
	'1006-0': [null, 'Iron Valiant', null, 'fairy', 'fighting'],
	'1007-0': [null, 'Koraidon', 'Apex Build', 'fighting', 'dragon'],
	'1007-1': [null, 'Koraidon', 'Limited Build', 'fighting', 'dragon'],
	'1008-0': [null, 'Miraidon', 'Ultimate Mode', 'electric', 'dragon'],
	'1008-1': [null, 'Miraidon', 'Low-Power Mode', 'electric', 'dragon'],
	'1009-0': [null, 'Walking Wake', null, 'water', 'dragon'],
	'1010-0': [null, 'Iron Leaves', null, 'grass', 'psychic'],
}

export const otherForms = {
	'201-0': [null, 'Unown', 'A', 'psychic', null],
	'201-1': [null, 'Unown', 'B', 'psychic', null],
	'201-2': [null, 'Unown', 'C', 'psychic', null],
	'201-3': [null, 'Unown', 'D', 'psychic', null],
	'201-4': [null, 'Unown', 'E', 'psychic', null],
	'201-5': [null, 'Unown', 'F', 'psychic', null],
	'201-6': [null, 'Unown', 'G', 'psychic', null],
	'201-7': [null, 'Unown', 'H', 'psychic', null],
	'201-8': [null, 'Unown', 'I', 'psychic', null],
	'201-9': [null, 'Unown', 'J', 'psychic', null],
	'201-10': [null, 'Unown', 'K', 'psychic', null],
	'201-11': [null, 'Unown', 'L', 'psychic', null],
	'201-12': [null, 'Unown', 'M', 'psychic', null],
	'201-13': [null, 'Unown', 'N', 'psychic', null],
	'201-14': [null, 'Unown', 'O', 'psychic', null],
	'201-15': [null, 'Unown', 'P', 'psychic', null],
	'201-16': [null, 'Unown', 'Q', 'psychic', null],
	'201-17': [null, 'Unown', 'R', 'psychic', null],
	'201-18': [null, 'Unown', 'S', 'psychic', null],
	'201-19': [null, 'Unown', 'T', 'psychic', null],
	'201-20': [null, 'Unown', 'U', 'psychic', null],
	'201-21': [null, 'Unown', 'V', 'psychic', null],
	'201-22': [null, 'Unown', 'W', 'psychic', null],
	'201-23': [null, 'Unown', 'X', 'psychic', null],
	'201-24': [null, 'Unown', 'Y', 'psychic', null],
	'201-25': [null, 'Unown', 'Z', 'psychic', null],
	'201-26': [null, 'Unown', '!', 'psychic', null],
	'201-27': [null, 'Unown', '?', 'psychic', null],
	'351-0': [null, 'Castform', 'Normal Form', 'normal', null],
	'351-1': [null, 'Castform', 'Sunny Form', 'fire', null],
	'351-2': [null, 'Castform', 'Rainy Form', 'water', null],
	'351-3': [null, 'Castform', 'Snowy Form', 'ice', null],
	'386-0': [null, 'Deoxys', 'Normal Forme', 'psychic', null],
	'386-1': [null, 'Deoxys', 'Attack Forme', 'psychic', null],
	'386-2': [null, 'Deoxys', 'Defense Forme', 'psychic', null],
	'386-3': [null, 'Deoxys', 'Speed Forme', 'psychic', null],
	'412-0': [null, 'Burmy', 'Plant Cloak', 'bug', null],
	'413-0': [null, 'Wormadam', 'Plant Cloak', 'bug', 'grass'],
	'412-1': [null, 'Burmy', 'Sandy Cloak', 'bug', null],
	'413-1': [null, 'Wormadam', 'Sandy Cloak', 'bug', 'ground'],
	'412-2': [null, 'Burmy', 'Trash Cloak', 'bug', null],
	'413-2': [null, 'Wormadam', 'Trash Cloak', 'bug', 'steel'],
	'421-0': [null, 'Cherrim', 'Overcast Form', 'grass', null],
	'421-1': [null, 'Cherrim', 'Sunshine Form', 'grass', null],
	'422-0': [null, 'Shellos', 'West Sea', 'water', null],
	'423-0': [null, 'Gastrodon', 'West Sea', 'water', 'ground'],
	'422-1': [null, 'Shellos', 'East Sea', 'water', null],
	'423-1': [null, 'Gastrodon', 'East Sea', 'water', 'ground'],
	'479-0': [null, 'Rotom', null, 'electric', 'ghost'],
	'479-1': ['Heat', 'Rotom', null, 'electric', 'fire'],
	'479-2': ['Wash', 'Rotom', null, 'electric', 'water'],
	'479-3': ['Frost', 'Rotom', null, 'electric', 'ice'],
	'479-4': ['Fan', 'Rotom', null, 'electric', 'flying'],
	'479-5': ['Mow', 'Rotom', null, 'electric', 'grass'],
	'483-0': [null, 'Dialga', null, 'steel', 'dragon'],
	'483-1': [null, 'Dialga', 'Origin Forme', 'steel', 'dragon'],
	'484-0': [null, 'Palkia', null, 'water', 'dragon'],
	'484-1': [null, 'Palkia', 'Origin Forme', 'water', 'dragon'],
	'487-0': [null, 'Giratina', 'Altered Forme', 'ghost', 'dragon'],
	'487-1': [null, 'Giratina', 'Origin Forme', 'ghost', 'dragon'],
	'492-0': [null, 'Shaymin', 'Land Forme', 'grass', null],
	'492-1': [null, 'Shaymin', 'Sky Forme', 'grass', 'flying'],
	'493-0': [null, 'Arceus', 'Blank Plate', 'normal', null],
	'493-1': [null, 'Arceus', 'Fist Plate', 'fighting', null],
	'493-2': [null, 'Arceus', 'Sky Plate', 'flying', null],
	'493-3': [null, 'Arceus', 'Toxic Plate', 'poison', null],
	'493-4': [null, 'Arceus', 'Earth Plate', 'ground', null],
	'493-5': [null, 'Arceus', 'Stone Plate', 'rock', null],
	'493-6': [null, 'Arceus', 'Insect Plate', 'bug', null],
	'493-7': [null, 'Arceus', 'Spooky Plate', 'ghost', null],
	'493-8': [null, 'Arceus', 'Iron Plate', 'steel', null],
	'493-9': [null, 'Arceus', 'Flame Plate', 'fire', null],
	'493-10': [null, 'Arceus', 'Splash Plate', 'water', null],
	'493-11': [null, 'Arceus', 'Meadow Plate', 'grass', null],
	'493-12': [null, 'Arceus', 'Zap Plate', 'electric', null],
	'493-13': [null, 'Arceus', 'Mind Plate', 'psychic', null],
	'493-14': [null, 'Arceus', 'Icicle Plate', 'ice', null],
	'493-15': [null, 'Arceus', 'Draco Plate', 'dragon', null],
	'493-16': [null, 'Arceus', 'Dread Plate', 'dark', null],
	'493-17': [null, 'Arceus', 'Pixie Plate', 'fairy', null],
	'521-0': [null, 'Unfezant', 'Male', 'normal', 'flying'],
	'521-1': [null, 'Unfezant', 'Female', 'normal', 'flying'],
	'554-0': [null, 'Darumaka', null, 'fire', null],
	'555-0': [null, 'Darmanitan', null, 'fire', null],
	'555-2': [null, 'Darmanitan', 'Zen Mode', 'fire', 'psychic'],
	'585-0': [null, 'Deerling', 'Spring Form', 'normal', 'grass'],
	'586-0': [null, 'Sawsbuck', 'Spring Form', 'normal', 'grass'],
	'585-1': [null, 'Deerling', 'Summer Form', 'normal', 'grass'],
	'586-1': [null, 'Sawsbuck', 'Summer Form', 'normal', 'grass'],
	'585-2': [null, 'Deerling', 'Autumn Form', 'normal', 'grass'],
	'586-2': [null, 'Sawsbuck', 'Autumn Form', 'normal', 'grass'],
	'585-3': [null, 'Deerling', 'Winter Form', 'normal', 'grass'],
	'586-3': [null, 'Sawsbuck', 'Winter Form', 'normal', 'grass'],
	'592-0': [null, 'Frillish', 'Male', 'water', 'ghost'],
	'593-0': [null, 'Jellicent', 'Male', 'water', 'ghost'],
	'592-1': [null, 'Frillish', 'Female', 'water', 'ghost'],
	'593-1': [null, 'Jellicent', 'Female', 'water', 'ghost'],
	'641-0': [null, 'Tornadus', 'Incarnate Forme', 'flying', null],
	'641-1': [null, 'Tornadus', 'Therian Forme', 'flying', null],
	'642-0': [null, 'Thundurus', 'Incarnate Forme', 'electric', 'flying'],
	'642-1': [null, 'Thundurus', 'Therian Forme', 'electric', 'flying'],
	'645-0': [null, 'Landorus', 'Incarnate Forme', 'ground', 'flying'],
	'645-1': [null, 'Landorus', 'Therian Forme', 'ground', 'flying'],
	'905-0': ['Hisuian', 'Enamorus', 'Incarnate Forme', 'fairy', 'flying'],
	'905-1': ['Hisuian', 'Enamorus', 'Therian Forme', 'fairy', 'flying'],
	'643-0': [null, 'Reshiram', null, 'dragon', 'fire'],
	'646-1': ['White', 'Kyurem', null, 'dragon', 'ice'],
	'646-0': [null, 'Kyurem', null, 'dragon', 'ice'],
	'646-2': ['Black', 'Kyurem', null, 'dragon', 'ice'],
	'644-0': [null, 'Zekrom', null, 'dragon', 'electric'],
	'647-0': [null, 'Keldeo', 'Ordinary Forme', 'water', 'fighting'],
	'647-1': [null, 'Keldeo', 'Resolute Forme', 'water', 'fighting'],
	'648-0': [null, 'Meloetta', 'Aria Forme', 'normal', 'psychic'],
	'648-1': [null, 'Meloetta', 'Pirouette Forme', 'normal', 'fighting'],
	'649-0': [null, 'Genesect', null, 'bug', 'steel'],
	'649-1': [null, 'Genesect', 'Douse Drive', 'bug', 'steel'],
	'649-2': [null, 'Genesect', 'Shock Drive', 'bug', 'steel'],
	'649-3': [null, 'Genesect', 'Burn Drive', 'bug', 'steel'],
	'649-4': [null, 'Genesect', 'Chill Drive', 'bug', 'steel'],
	...region6_mega,
	'666-0': [null, 'Vivillon', 'Icy Snow Pattern', 'bug', 'flying'],
	'666-1': [null, 'Vivillon', 'Polar Pattern', 'bug', 'flying'],
	'666-2': [null, 'Vivillon', 'Tundra Pattern', 'bug', 'flying'],
	'666-3': [null, 'Vivillon', 'Continental Pattern', 'bug', 'flying'],
	'666-4': [null, 'Vivillon', 'Garden Pattern', 'bug', 'flying'],
	'666-5': [null, 'Vivillon', 'Elegant Pattern', 'bug', 'flying'],
	'666-6': [null, 'Vivillon', 'Meadow Pattern', 'bug', 'flying'],
	'666-7': [null, 'Vivillon', 'Modern Pattern', 'bug', 'flying'],
	'666-8': [null, 'Vivillon', 'Marine Pattern', 'bug', 'flying'],
	'666-9': [null, 'Vivillon', 'Archipelago Pattern', 'bug', 'flying'],
	'666-10': [null, 'Vivillon', 'High Plains Pattern', 'bug', 'flying'],
	'666-11': [null, 'Vivillon', 'Sandstorm Pattern', 'bug', 'flying'],
	'666-12': [null, 'Vivillon', 'River Pattern', 'bug', 'flying'],
	'666-13': [null, 'Vivillon', 'Monsoon Pattern', 'bug', 'flying'],
	'666-14': [null, 'Vivillon', 'Savanna Pattern', 'bug', 'flying'],
	'666-15': [null, 'Vivillon', 'Sun Pattern', 'bug', 'flying'],
	'666-16': [null, 'Vivillon', 'Ocean Pattern', 'bug', 'flying'],
	'666-17': [null, 'Vivillon', 'Jungle Pattern', 'bug', 'flying'],
	'666-18': [null, 'Vivillon', 'Fancy Pattern', 'bug', 'flying'],
	'666-19': [null, 'Vivillon', 'Poké Ball Pattern', 'bug', 'flying'],
	'668-0': [null, 'Litleo', 'Male', 'fire', 'normal'],
	'668-1': [null, 'Litleo', 'Female', 'fire', 'normal'],
	'669-0': [null, 'Flabébé', 'Red Flower', 'fairy', null],
	'670-0': [null, 'Floette', 'Red Flower', 'fairy', null],
	'671-0': [null, 'Florges', 'Red Flower', 'fairy', null],
	'669-1': [null, 'Flabébé', 'Yellow Flower', 'fairy', null],
	'670-1': [null, 'Floette', 'Yellow Flower', 'fairy', null],
	'671-1': [null, 'Florges', 'Yellow Flower', 'fairy', null],
	'669-2': [null, 'Flabébé', 'Orange Flower', 'fairy', null],
	'670-2': [null, 'Floette', 'Orange Flower', 'fairy', null],
	'671-2': [null, 'Florges', 'Orange Flower', 'fairy', null],
	'669-3': [null, 'Flabébé', 'Blue Flower', 'fairy', null],
	'670-3': [null, 'Floette', 'Blue Flower', 'fairy', null],
	'671-3': [null, 'Florges', 'Blue Flower', 'fairy', null],
	'669-4': [null, 'Flabébé', 'White Flower', 'fairy', null],
	'670-4': [null, 'Floette', 'White Flower', 'fairy', null],
	'671-4': [null, 'Florges', 'White Flower', 'fairy', null],
	'670-5': [null, 'Floette', 'Eternal Flower', 'fairy', null],
	'676-0': [null, 'Furfrou', 'Natural Form', 'normal', null],
	'676-1': [null, 'Furfrou', 'Heart Trim', 'normal', null],
	'676-2': [null, 'Furfrou', 'Star Trim', 'normal', null],
	'676-3': [null, 'Furfrou', 'Diamond Trim', 'normal', null],
	'676-4': [null, 'Furfrou', 'Debutante Trim', 'normal', null],
	'676-5': [null, 'Furfrou', 'Matron Trim', 'normal', null],
	'676-6': [null, 'Furfrou', 'Dandy Trim', 'normal', null],
	'676-7': [null, 'Furfrou', 'La Reine Trim', 'normal', null],
	'676-8': [null, 'Furfrou', 'Kabuki Trim', 'normal', null],
	'676-9': [null, 'Furfrou', 'Pharaoh Trim', 'normal', null],
	'678-0': [null, 'Meowstic', 'Male', 'psychic', null],
	'678-1': [null, 'Meowstic', 'Female', 'psychic', null],
	'681-0': [null, 'Aegislash', 'Shield Forme', 'steel', 'ghost'],
	'681-1': [null, 'Aegislash', 'Blade Forme', 'steel', 'ghost'],
	'710-1': [null, 'Pumpkaboo', 'Small Size', 'ghost', 'grass'],
	'710-0': [null, 'Pumpkaboo', 'Average Size', 'ghost', 'grass'],
	'710-2': [null, 'Pumpkaboo', 'Large Size', 'ghost', 'grass'],
	'710-3': [null, 'Pumpkaboo', 'Super Size', 'ghost', 'grass'],
	'711-1': [null, 'Gourgeist', 'Small Size', 'ghost', 'grass'],
	'711-0': [null, 'Gourgeist', 'Average Size', 'ghost', 'grass'],
	'711-2': [null, 'Gourgeist', 'Large Size', 'ghost', 'grass'],
	'711-3': [null, 'Gourgeist', 'Super Size', 'ghost', 'grass'],
	'716-0': [null, 'Xerneas', 'Active Mode', 'fairy', null],
	'716-1': [null, 'Xerneas', 'Neutral Mode', 'fairy', null],
	'718-1': [null, 'Zygarde', '10% Forme', 'dragon', 'ground'],
	'718-0': [null, 'Zygarde', '50% Forme', 'dragon', 'ground'],
	'718-4': [null, 'Zygarde', 'Complete Forme', 'dragon', 'ground'],
	'720-0': [null, 'Hoopa', 'Confined', 'psychic', 'ghost'],
	'720-1': [null, 'Hoopa', 'Unbound', 'psychic', 'dark'],
	...region7_old,
	'741-0': [null, 'Oricorio', 'Baile Style', 'fire', 'flying'],
	'741-1': [null, 'Oricorio', 'Pom-Pom Style', 'electric', 'flying'],
	'741-2': [null, 'Oricorio', "Pa'u Style", 'psychic', 'flying'],
	'741-3': [null, 'Oricorio', 'Sensu Style', 'ghost', 'flying'],
	'745-0': [null, 'Lycanroc', 'Midday Form', 'rock', null],
	'745-1': [null, 'Lycanroc', 'Midnight Form', 'rock', null],
	'745-2': [null, 'Lycanroc', 'Dusk Form', 'rock', null],
	'746-0': [null, 'Wishiwashi', 'Solo Form', 'water', null],
	'746-1': [null, 'Wishiwashi', 'School Form', 'water', null],
	'774-0': [null, 'Minior', 'Meteor Form', 'rock', 'flying'],
	'774-7': [null, 'Minior', 'Red Core', 'rock', 'flying'],
	'774-8': [null, 'Minior', 'Orange Core', 'rock', 'flying'],
	'774-9': [null, 'Minior', 'Yellow Core', 'rock', 'flying'],
	'774-10': [null, 'Minior', 'Green Core', 'rock', 'flying'],
	'774-11': [null, 'Minior', 'Blue Core', 'rock', 'flying'],
	'774-12': [null, 'Minior', 'Indigo Core', 'rock', 'flying'],
	'774-13': [null, 'Minior', 'Violet Core', 'rock', 'flying'],
	'800-3': ['Ultra', 'Necrozma', null, 'psychic', 'dragon'],
	'800-1': ['Dusk Mane', 'Necrozma', null, 'psychic', 'steel'],
	'791-0': [null, 'Solgaleo', null, 'psychic', 'steel'],
	'792-0': [null, 'Lunala', null, 'psychic', 'ghost'],
	'800-2': ['Dawn Wings', 'Necrozma', null, 'psychic', 'ghost'],
	'800-0': [null, 'Necrozma', null, 'psychic', null],
	'801-0': [null, 'Magearna', null, 'steel', 'fairy'],
	'801-1': ['Original Color', 'Magearna', null, 'steel', 'fairy'],
	...region7_totems,
	...region8a_old,
	...region8a_gmax,
	'845-0': [null, 'Cramorant', null, 'flying', 'water'],
	'845-1': [null, 'Cramorant', 'Gulping Form', 'flying', 'water'],
	'845-2': [null, 'Cramorant', 'Gorging Form', 'flying', 'water'],
	'849-0': [null, 'Toxtricity', 'Amped Form', 'electric', 'poison'],
	'849-1': [null, 'Toxtricity', 'Low Key Form', 'electric', 'poison'],
	'869-0': [null, 'Alcremie', 'Vanilla Cream', 'fairy', null],
	'869-1': [null, 'Alcremie', 'Ruby Cream', 'fairy', null],
	'869-2': [null, 'Alcremie', 'Matcha Cream', 'fairy', null],
	'869-3': [null, 'Alcremie', 'Mint Cream', 'fairy', null],
	'869-4': [null, 'Alcremie', 'Lemon Cream', 'fairy', null],
	'869-5': [null, 'Alcremie', 'Salted Cream', 'fairy', null],
	'869-6': [null, 'Alcremie', 'Ruby Swirl', 'fairy', null],
	'869-7': [null, 'Alcremie', 'Caramel Swirl', 'fairy', null],
	'869-8': [null, 'Alcremie', 'Rainbow Swirl', 'fairy', null],
	'875-0': [null, 'Eiscue', 'Ice Face', 'ice', null],
	'875-1': [null, 'Eiscue', 'Noice Face', 'ice', null],
	'876-0': [null, 'Indeedee', 'Male', 'psychic', null],
	'876-1': [null, 'Indeedee', 'Female', 'psychic', null],
	'877-0': [null, 'Morpeko', 'Full Belly Mode', 'electric', 'dark'],
	'877-1': [null, 'Morpeko', 'Hangry Mode', 'dark', 'electric'],
	'888-0': [null, 'Zacian', 'Hero of Many Battles', 'fairy', null],
	'888-1': [null, 'Zacian', 'Crowned Sword', 'fairy', 'steel'],
	'889-0': [null, 'Zamazenta', 'Hero of Many Battles', 'fighting', null],
	'889-1': [null, 'Zamazenta', 'Crowned Shield', 'fighting', 'steel'],
	'890-0': [null, 'Eternatus', null, 'poison', 'dragon'],
	'890-1': ['Eternamax', 'Eternatus', null, 'poison', 'dragon'],
	'893-0': [null, 'Zarude', null, 'dark', 'grass'],
	'893-1': ['Dada', 'Zarude', null, 'dark', 'grass'],
	'896-0': [null, 'Glastrier', null, 'ice', null],
	'898-1': [null, 'Calyrex', 'Ice Rider', 'psychic', 'ice'],
	'898-0': [null, 'Calyrex', null, 'psychic', 'grass'],
	'898-2': [null, 'Calyrex', 'Shadow Rider', 'psychic', 'ghost'],
	'897-0': [null, 'Spectrier', null, 'ghost', null],
	...region8b_old,
	'916-0': [null, 'Oinkologne', 'Male', 'normal', null],
	'916-1': [null, 'Oinkologne', 'Female', 'normal', null],
	'925-0': [null, 'Maushold', 'Family of Three', 'normal', null],
	'925-1': [null, 'Maushold', 'Family of Four', 'normal', null],
	'931-0': [null, 'Squawkabilly', 'Green Plummage', 'normal', 'flying'],
	'931-1': [null, 'Squawkabilly', 'Blue Plummage', 'normal', 'flying'],
	'931-2': [null, 'Squawkabilly', 'Yellow Plummage', 'normal', 'flying'],
	'931-3': [null, 'Squawkabilly', 'White Plummage', 'normal', 'flying'],
	'964-0': [null, 'Palafin', 'Zero Form', 'water', null],
	'964-1': [null, 'Palafin', 'Hero Form', 'water', null],
	'978-0': [null, 'Tatsugiri', 'Curly Form', 'dragon', 'water'],
	'978-1': [null, 'Tatsugiri', 'Droopy Form', 'dragon', 'water'],
	'978-2': [null, 'Tatsugiri', 'Stretchy Form', 'dragon', 'water'],
	...region9a_old,
	'999-1': [null, 'Gimmighoul', 'Roaming Form', 'ghost', null],
	'999-0': [null, 'Gimmighoul', 'Chest Form', 'ghost', null],
	'1007-1': [null, 'Koraidon', 'Limited Build', 'fighting', 'dragon'],
	'1007-0': [null, 'Koraidon', 'Apex Build', 'fighting', 'dragon'],
	'967-0': [null, 'Cyclizar', null, 'dragon', null],
	'1008-0': [null, 'Miraidon', 'Ultimate Mode', 'electric', 'dragon'],
	'1008-1': [null, 'Miraidon', 'Low-Power Mode', 'electric', 'dragon'],
}

export const nationalDex = {
	...region1_new,
	...region2_new,
	...region3_new,
	...region4_new,
	...region5_new,
	...region6_new,
	...region7_new,
	...region8a_new,
	...region8b_new,
	...region9a_new
}

export const regionalVariants = {
	...region7_old,
	...region8a_old,
	...region8b_old,
	...region9a_old
}

export const masterlist = {
	...nationalDex,
	...otherForms
}

// export const region1_all = {...region1_new}
// export const region2_all = {...region2_new}
// export const region3_all = {...region3_new}
// export const region4_all = {...region4_new}
// export const region5_all = {...region5_new}
export const region6_all = {...region6_mega, ...region6_new}
export const region7_all = {...region7_old, ...region7_new, ...region7_totems}
export const region8a_all = {...region8a_old, ...region8a_new, ...region8a_gmax}
export const region8b_all = {...region8b_old, ...region8b_new}
export const region9a_all = {...region9a_old, ...region9a_new}

export const fetchAllForms = id => Object.keys(masterlist)
	.filter(key => key.startsWith(`${id}-`))
	.reduce((obj, key) => {
		obj[key] = masterlist[key];
		return obj;
	}, {});

export const hasSprite = id => Object.keys(masterlist).includes(id)

export const formToSprite = {
	'pikachu-rock-star': '25-0',
	'pikachu-belle': '25-0',
	'pikachu-pop-star': '25-0',
	'pikachu-phd': '25-0',
	'pikachu-libre': '25-0',
	'pikachu-cosplay': '25-0',
	'pikachu-starter': '25-0',
	'pikachu-original-cap': '25-1',
	'pikachu-hoenn-cap': '25-2',
	'pikachu-sinnoh-cap': '25-3',
	'pikachu-unova-cap': '25-4',
	'pikachu-kalos-cap': '25-5',
	'pikachu-alola-cap': '25-6',
	'pikachu-partner-cap': '25-7',
	'pikachu-world-cap': '25-8',
	'eevee-starter': '133-0',
	'castform-sunny': '351-1',
	'castform-rainy': '351-2',
	'castform-snowy': '351-3',
	'deoxys-attack': '386-1',
	'deoxys-defense': '386-2',
	'deoxys-speed': '386-3',
	'wormadam-sandy': '413-1',
	'wormadam-trash': '413-2',
	'rotom-heat': '479-1',
	'rotom-wash': '479-2',
	'rotom-frost': '479-3',
	'rotom-fan': '479-4',
	'rotom-mow': '479-5',
	'basculin-blue-striped': '550-1',
	'basculin-hisui': '550-2',
	'basculin-white-striped': '550-2',
	'basculegion-hisui': '902-0',
	'basculegion-hisui-female': '902-1',
	'basculegion-female': '902-1',
	'darmanitan-zen': '555-2',
	'darmanitan-galar-standard': '555-1',
	'shaymin-sky': '492-1',
	'tornadus-therian': '641-1',
	'thundurus-therian': '642-1',
	'landorus-therian': '645-1',
	'enamorus-therian': '905-1',
	'kyurem-black': '646-1',
	'kyurem-white': '646-2',
	'meloetta-pirouette': '648-1',
	'keldeo-resolute': '647-1',
	'venusaur-mega': '3-1',
	'charizard-mega-x': '6-1',
	'charizard-mega-y': '6-2',
	'blastoise-mega': '9-1',
	'beedrill-mega': '15-1',
	'pidgeot-mega': '18-1',
	'alakazam-mega': '65-1',
	'slowbro-mega': '80-1',
	'gengar-mega': '94-1',
	'kangaskhan-mega': '115-1',
	'pinsir-mega': '127-1',
	'gyarados-mega': '130-1',
	'aerodactyl-mega': '142-1',
	'mewtwo-mega-x': '150-1',
	'mewtwo-mega-y': '150-2',
	'ampharos-mega': '181-1',
	'scizor-mega': '212-1',
	'steelix-mega': '208-1',
	'heracross-mega': '214-1',
	'houndoom-mega': '229-1',
	'tyranitar-mega': '248-1',
	'sceptile-mega': '254-1',
	'blaziken-mega': '257-1',
	'swampert-mega': '260-1',
	'gardevoir-mega': '282-1',
	'sableye-mega': '302-1',
	'mawile-mega': '303-1',
	'aggron-mega': '306-1',
	'medicham-mega': '308-1',
	'manectric-mega': '310-1',
	'sharpedo-mega': '319-1',
	'camerupt-mega': '323-1',
	'altaria-mega': '334-1',
	'banette-mega': '354-1',
	'absol-mega': '359-1',
	'glalie-mega': '362-1',
	'salamence-mega': '373-1',
	'metagross-mega': '376-1',
	'latias-mega': '380-1',
	'latios-mega': '381-1',
	'kyogre-primal': '382-1',
	'groudon-primal': '383-1',
	'rayquaza-mega': '384-1',
	'lopunny-mega': '428-1',
	'garchomp-mega': '445-1',
	'lucario-mega': '448-1',
	'abomasnow-mega': '460-1',
	'gallade-mega': '475-1',
	'audino-mega': '531-1',
	'greninja-battle-bond': '658-2',
	'greninja-ash': '658-2',
	'floette-eternal': '670-5',
	'meowstic-female': '678-1',
	'aegislash-blade': '681-1',
	'pumpkaboo-small': '710-1',
	'pumpkaboo-large': '710-2',
	'pumpkaboo-super': '710-3',
	'gourgeist-small': '711-1',
	'gourgeist-large': '711-2',
	'gourgeist-super': '711-3',
	'zygarde-10': '718-1',
	'zygarde-10-power-construct': '718-1',
	'zygarde-50-power-construct': '718-1',
	'zygarde-complete': '718-4',
	'diancie-mega': '719-1',
	'hoopa-unbound': '720-1',
	'rattata-alola': '19-1',
	'raticate-alola': '20-1',
	'raichu-alola': '26-1',
	'sandshrew-alola': '27-1',
	'sandslash-alola': '28-1',
	'vulpix-alola': '37-1',
	'ninetales-alola': '38-1',
	'diglett-alola': '50-1',
	'dugtrio-alola': '51-1',
	'meowth-alola': '52-1',
	'persian-alola': '53-1',
	'geodude-alola': '74-1',
	'graveler-alola': '75-1',
	'golem-alola': '76-1',
	'grimer-alola': '88-1',
	'muk-alola': '89-1',
	'exeggutor-alola': '103-1',
	'raticate-totem-alola': '20-1',
	'marowak-totem-alola': '105-1',
	'gumshoos-totem': '735-0',
	'vikavolt-totem': '738-0',
	'oricorio-pom-pom': '741-1',
	'oricorio-pau': '741-2',
	'oricorio-sensu': '741-3',
	'ribombee-totem': '743-0',
	'rockruff-own-tempo': '744-0',
	'lycanroc-midnight': '745-1',
	'lycanroc-dusk': '745-2',
	'wishiwashi-school': '746-1',
	'araquanid-totem': '752-0',
	'lurantis-totem': '754-0',
	'salazzle-totem': '758-0',
	'minior-red-meteor': '774-0',
	'minior-orange-meteor': '774-0',
	'minior-yellow-meteor': '774-0',
	'minior-green-meteor': '774-0',
	'minior-blue-meteor': '774-0',
	'minior-indigo-meteor': '774-0',
	'minior-violet-meteor': '774-0',
	'minior-red': '774-7',
	'minior-orange': '774-8',
	'minior-yellow': '774-9',
	'minior-green': '774-10',
	'minior-blue': '774-11',
	'minior-indigo': '774-12',
	'minior-violet': '774-13',
	'togedemaru-totem': '777-0',
	'mimikyu-totem-disguised': '778-0',
	'mimikyu-totem-busted': '778-0',
	'mimikyu-busted': '778-0',
	'kommo-o-totem': '784-0',
	'marowak-totem': '105-1',
	'marowak-alola': '105-1',
	'necrozma-dusk': '800-1',
	'necrozma-dawn': '800-2',
	'necrozma-ultra': '800-3',
	'magearna-original': '801-1',
	'meowth-galar': '52-2',
	'perrserker-galar': '863-0',
	'ponyta-galar': '77-1',
	'rapidash-galar': '78-1',
	'slowpoke-galar': '79-1',
	'slowbro-galar': '80-2',
	'slowking-galar': '199-1',
	'farfetchd-galar': '83-1',
	'sirfetchd': '865-0',
	'weezing-galar': '110-1',
	'mr-mime-galar': '122-1',
	'mr-rime': '866-0',
	'articuno-galar': '144-1',
	'zapdos-galar': '145-1',
	'moltres-galar': '146-1',
	'corsola-galar': '222-1',
	'cursola-galar': '864-0',
	'zigzagoon-galar': '263-1',
	'linoone-galar': '264-1',
	'obstagoon-galar': '862-0',
	'darumaka-galar': '554-1',
	'darmanitan-galar': '555-1',
	'darmanitan-galar-zen': '555-3',
	'yamask-galar': '562-1',
	'runerigus-galar': '867-0',
	'stunfisk-galar': '618-1',
	'cramorant-gulping': '845-1',
	'cramorant-gorging': '845-2',
	'zacian-crowned': '888-1',
	'zamazenta-crowned': '889-1',
	'urshifu-rapid-strike': '892-0',
	'venusaur-gmax': '3-0',
	'charizard-gmax': '6-0',
	'blastoise-gmax': '9-0',
	'butterfree-gmax': '12-0',
	'pikachu-gmax': '25-0',
	'meowth-gmax': '52-0',
	'machamp-gmax': '68-0',
	'gengar-gmax': '94-0',
	'kingler-gmax': '99-0',
	'lapras-gmax': '131-0',
	'eevee-gmax': '133-0',
	'snorlax-gmax': '143-0',
	'garbodor-gmax': '569-0',
	'melmetal-gmax': '809-0',
	'rillaboom-gmax': '812-0',
	'cinderace-gmax': '815-0',
	'inteleon-gmax': '818-0',
	'corviknight-gmax': '823-0',
	'orbeetle-gmax': '826-0',
	'drednaw-gmax': '834-0',
	'coalossal-gmax': '839-0',
	'flapple-gmax': '841-0',
	'appletun-gmax': '842-0',
	'sandaconda-gmax': '844-0',
	'toxtricity-low-key': '849-1',
	'toxtricity-amped-gmax': '849-0',
	'toxtricity-low-key-gmax': '849-1',
	'centiskorch-gmax': '851-0',
	'hatterene-gmax': '858-0',
	'grimmsnarl-gmax': '861-0',
	'alcremie-gmax': '869-0',
	'eiscue-noice': '875-1',
	'copperajah-gmax': '879-0',
	'duraludon-gmax': '884-0',
	'urshifu-single-strike-gmax': '892-0',
	'urshifu-rapid-strike-gmax': '892-0',
	'indeedee-female': '876-1',
	'morpeko-hangry': '877-1',
	'eternatus-eternamax': '890-0',
	'zarude-dada': '893-1',
	'calyrex-ice': '898-1',
	'calyrex-shadow': '898-2',
	'growlithe-hisui': '58-1',
	'arcanine-hisui': '59-1',
	'voltorb-hisui': '100-1',
	'electrode-hisui': '101-1',
	'kleavor-hisui': '900-0',
	'typhlosion-hisui': '157-1',
	'qwilfish-hisui': '211-1',
	'overqwil-hisui': '904-0',
	'sneasel-hisui': '215-1',
	'sneasler-hisui': '903-0',
	'ursaluna-hisui': '901-0',
	'wyrdeer-hisui': '899-0',
	'samurott-hisui': '503-1',
	'lilligant-hisui': '549-1',
	'zorua-hisui': '570-1',
	'zoroark-hisui': '571-1',
	'braviary-hisui': '628-1',
	'sliggoo-hisui': '705-1',
	'goodra-hisui': '706-1',
	'avalugg-hisui': '713-1',
	'decidueye-hisui': '724-1',
	'dialga-origin': '483-1',
	'palkia-origin': '484-1',
	'giratina-origin': '487-1',
	'tauros-paldea-combat-breed': '128-1',
	'tauros-paldea-blaze-breed': '128-2',
	'tauros-paldea-aqua-breed': '128-3',
	'wooper-paldea': '194-1',
	'oinkologne-female': '916-1',
	'dudunsparce-three-segment': '982-0',
	'maushold-family-of-three': '925-1',
	'squawkabilly-blue-plumage': '931-1',
	'squawkabilly-yellow-plumage': '931-2',
	'squawkabilly-white-plumage': '931-3',
	'palafin-hero': '964-1',
	'tatsugiri-droopy': '978-1',
	'tatsugiri-stretchy': '978-2',
	'gimmighoul-roaming': '999-1',
	'koraidon-limited-build': '1007-1',
	'koraidon-sprinting-build': '1007-1',
	'koraidon-swimming-build': '1007-1',
	'koraidon-gliding-build': '1007-1',
	'miraidon-low-power-mode': '1008-1',
	'miraidon-drive-mode': '1008-1',
	'miraidon-aquatic-mode': '1008-1',
	'miraidon-glide-mode': '1008-1',
}